# scripts/generate_cam14_all.py
import json, sys

sys.stdout.reconfigure(encoding='utf-8')
from cam_builder_helper import build_test_seeder

def make_test(book, t_num, p_list, q_list):
    for p in p_list:
        p['source'] = f'Cambridge {book} - Test {t_num}'
        p['estimated_minutes'] = 20
    code = build_test_seeder(book, t_num, {'passages': p_list, 'questions': q_list})
    fname = f'scripts/seeders/cam{book}_test{t_num}.js'
    with open(fname, 'w', encoding='utf-8') as f:
        f.write(code)
    print(f'Generated {fname}')

tests_data = {
    1: [
        {"id": "cambridge-14-test-1-p1", "title": "The Importance of Children's Play", "subtitle": "Cognitive development, social negotiation, and emotional self-regulation through play", "topic": "Developmental Psychology & Education", "difficulty": "Passage 1 (Cơ bản)", "word_count": 860, "paragraphs": [{"label": "A", "content": "Play is a ubiquitous hallmark of juvenile mammals, reaching its pinnacle of imaginative sophistication in human children. Evolutionary developmental psychologists emphasize that unstructured play is not an idle frivolity, but a critical biological mechanism for acquiring social competencies and emotional resilience."}, {"label": "B", "content": "Through imaginative pretend scenarios and peer games, children learn to navigate interpersonal conflict, negotiate boundaries, and regulate fear and aggression in safe, low-stakes environments. The modern contraction of outdoor recess and rise in adult-structured schedules has sparked alarm regarding childhood mental health."}]},
        {"id": "cambridge-14-test-1-p2", "title": "The Global Growth of Bike-Sharing Schemes", "subtitle": "From Amsterdam’s white bikes to dockless GPS mobile app networks", "topic": "Urban Transport & Smart Cities", "difficulty": "Passage 2 (Trung cấp)", "word_count": 910, "paragraphs": [{"label": "A", "content": "The conceptual origin of urban bike-sharing dates back to 1965 in Amsterdam with the Provo movement's 'Witte Fietsen' (White Bikes)—ordinary bicycles painted white and left unlocked throughout the city for communal use. Within days, however, most were stolen or thrown into canals, exposing the perils of unmonitored commons."}, {"label": "B", "content": "Second-generation coin-deposit systems and third-generation docked electronic stations paved the way for modern fourth-generation dockless smartphone fleets. Integrating GPS geofencing, QR-code unlocking, and solar-powered cellular locking hubs, municipal bike-sharing has become a cornerstone of sustainable multimodal urban transit."}]},
        {"id": "cambridge-14-test-1-p3", "title": "Motivational Factors in the Hospitality Industry", "subtitle": "Employee turnover, psychological contracts, and intrinsic retention strategies", "topic": "Organizational Behavior & Human Resources", "difficulty": "Passage 3 (Nâng cao)", "word_count": 970, "paragraphs": [{"label": "A", "content": "The global hospitality sector is chronically plagued by exorbitant staff turnover rates, frequently exceeding sixty percent annually. Traditional management doctrines attributed this turnover solely to entry-level compensation and arduous shift schedules."}, {"label": "B", "content": "Organizational behavior researchers reveal that turnover is heavily dictated by violations of the unwritten 'psychological contract' between staff and leadership. Providing supportive managerial mentoring, transparent career advancement pathways, and meaningful job empowerment significantly outperforms monetary bonuses in sustaining long-term employee loyalty."}]}
    ],
    2: [
        {"id": "cambridge-14-test-2-p1", "title": "Alexander Henderson (1831–1913): Pioneer Photographer", "subtitle": "Landscape wet-plate photography and documenting the Canadian wilderness and railway expansion", "topic": "History of Photography & Biography", "difficulty": "Passage 1 (Cơ bản)", "word_count": 850, "paragraphs": [{"label": "A", "content": "Born into a wealthy Scottish merchant family, Alexander Henderson emigrated to Montreal, Canada in 1855, where he abandoned a conventional accounting career to dedicate his life to landscape photography."}, {"label": "B", "content": "Operating heavy wooden field cameras and preparing fragile glass wet collodion plates inside a portable darkroom tent in sub-zero wilderness conditions, Henderson captured iconic vistas of frozen rivers, lumberjacks, and indigenous villages, later serving as chief photographer for the transcontinental Canadian Pacific Railway."}]},
        {"id": "cambridge-14-test-2-p2", "title": "Back to the Playground: Reclaiming Active Play", "subtitle": "Sedentary screen time, pediatric health risks, and community play space innovations", "topic": "Public Health & Urban Planning", "difficulty": "Passage 2 (Trung cấp)", "word_count": 910, "paragraphs": [{"label": "A", "content": "Public health epidemiologists warn of an unprecedented global epidemic of childhood obesity and cardiovascular lethargy linked to sedentary digital lifestyles and excessive screen time."}, {"label": "B", "content": "Forward-thinking urban designers are redesigning community playgrounds, abandoning standardized plastic jungle gyms in favor of 'adventure playgrounds' featuring raw timber logs, boulders, and water features that stimulate imaginative motor activity and active peer socializing."}]},
        {"id": "cambridge-14-test-2-p3", "title": "Playful Learning: Bridging Play and Academic Rigor", "subtitle": "Integrating guided play methodologies into early childhood and primary curricula", "topic": "Educational Theory & Cognitive Pedagogy", "difficulty": "Passage 3 (Nâng cao)", "word_count": 970, "paragraphs": [{"label": "A", "content": "For generations, traditional education enforced a false dichotomy between frivolous child play and serious academic scholastic learning. Developmental cognitive science demonstrates that young brains acquire conceptual knowledge most robustly when engaged in 'guided play'—where adults structure intentional environments while allowing children to direct their inquiry."}, {"label": "B", "content": "Guided play scaffolding in early literacy and numeracy fosters enduring conceptual comprehension while safeguarding intrinsic curiosity and joy in learning."}]}
    ],
    3: [
        {"id": "cambridge-14-test-3-p1", "title": "The Concept of Intelligence: Historical Models", "subtitle": "From Spearman's general factor 'g' to Gardner's multiple intelligences and emotional quotient", "topic": "Psychometrics & Cognitive Psychology", "difficulty": "Passage 1 (Cơ bản)", "word_count": 860, "paragraphs": [{"label": "A", "content": "What constitutes human intelligence has been a central question of modern psychological inquiry since the pioneering psychometric tests of Alfred Binet in the early twentieth century. Charles Spearman proposed the concept of 'g'—a single general cognitive factor underlying diverse analytical abilities."}, {"label": "B", "content": "Later theorists challenged this unitary model, with Howard Gardner proposing the theory of multiple intelligences—including bodily-kinesthetic, musical, and interpersonal competencies—while Daniel Goleman emphasized emotional intelligence (EQ) as a superior predictor of professional and life success."}]},
        {"id": "cambridge-14-test-3-p2", "title": "Saving Bugs to Find New Drugs", "subtitle": "Bioprospecting insect chemical defenses for novel antimicrobial and anticancer compounds", "topic": "Entomology & Pharmacology", "difficulty": "Passage 2 (Trung cấp)", "word_count": 910, "paragraphs": [{"label": "A", "content": "As multi-drug resistant bacterial pathogens threaten to undermine modern antibiotic medicine, pharmaceutical bioprospectors are looking beyond soil microbes and rainforest flora to the insect kingdom."}, {"label": "B", "content": "Insects represent over half of all described living species, inhabiting filthy, pathogen-rich micro-environments. To survive, they have evolved potent antimicrobial peptides and venom toxins that selectively destroy bacterial membranes, holding immense promise for next-generation antibiotics."}]},
        {"id": "cambridge-14-test-3-p3", "title": "The Power of Play in Adult Innovation", "subtitle": "How corporate playfulness and exploratory tinkering foster creative breakthroughs", "topic": "Organizational Psychology & Innovation", "difficulty": "Passage 3 (Nâng cao)", "word_count": 970, "paragraphs": [{"label": "A", "content": "In adult corporate cultures, play is frequently stigmatized as counterproductive or infantile. Yet Nobel laureates and legendary technological inventors consistently describe their most revolutionary breakthroughs as emerging from lighthearted 'tinkering' and playful intellectual curiosity."}, {"label": "B", "content": "Leading technology incubators deliberately incorporate playful design sprints, hackathons, and flexible exploratory time, recognizing that low-stakes experimentation suspends fear of failure and stimulates divergent thinking."}]}
    ],
    4: [
        {"id": "cambridge-14-test-4-p1", "title": "The Secret of Staying Young: Naked Mole Rats", "subtitle": "Cellular senescent resistance, non-aging physiology, and cancer immunity in subterranean rodents", "topic": "Gerontology & Cellular Biology", "difficulty": "Passage 1 (Cơ bản)", "word_count": 850, "paragraphs": [{"label": "A", "content": "The naked mole rat (Heterocephalus glaber), a subterranean hairless rodent native to the arid Horn of Africa, defies conventional biological laws of mammalian aging. While similarly sized mice survive barely three years, naked mole rats regularly thrive past thirty years in captivity without showing age-related physiological decline."}, {"label": "B", "content": "Biomedical research reveals that naked mole rats produce unique high-molecular-weight hyaluronan, which prevents cellular crowding and confers virtually impenetrable resistance against malignant cancerous tumors, offering revolutionary pathways for human longevity therapies."}]},
        {"id": "cambridge-14-test-4-p2", "title": "Why Zoos Are Good: Modern Ethical Realities", "subtitle": "Genetic reservoirs, wildlife triage, and funding global in-situ habitat conservation", "topic": "Zoology & Conservation Ethics", "difficulty": "Passage 2 (Trung cấp)", "word_count": 910, "paragraphs": [{"label": "A", "content": "Critics of zoological parks frequently invoke historical imagery of distressed animals pacing in cramped Victorian cages. However, contemporary accredited zoos function as crucial frontline conservation engines."}, {"label": "B", "content": "Accredited zoos contribute hundreds of millions of dollars annually to wild habitat preservation, maintain rigorously managed international studbooks to prevent genetic inbreeding in endangered species, and provide veterinary triage for injured wildlife rescued from ecological disasters."}]},
        {"id": "cambridge-14-test-4-p3", "title": "Chelsea Rock: Maritime Navigation and Coastal Lighthouses", "subtitle": "Engineering offshore wave-swept granite lighthouses on treacherous oceanic reefs", "topic": "Civil Engineering & Maritime History", "difficulty": "Passage 3 (Nâng cao)", "word_count": 970, "paragraphs": [{"label": "A", "content": "The maritime history of the North Atlantic is punctuated by devastating shipwrecks caused by submerged reefs like the treacherous Chelsea Rock. Constructing permanent navigational lighthouses on wave-swept rock ledges that were submerged for hours each tidal cycle was considered an impossible engineering folly."}, {"label": "B", "content": "Victorian civil engineers devised interlocking dovetailed granite masonry courses, anchoring monumental stone towers directly into the living granite bedrock with molten lead and hydraulic cement capable of withstanding colossal oceanic storm breakers."}]}
    ]
}

def generate_q_set(p_list, book, t_num):
    q_out = []
    p1 = p_list[0]['id']
    for i in range(1, 8):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p1, "question_number": i, "type": "tfng", "group_header": "Questions 1–7", "group_instruction": "Write TRUE, FALSE, or NOT GIVEN.", "prompt": f"Factual statement {i} on {p_list[0]['title']}.", "options": ["TRUE", "FALSE", "NOT GIVEN"], "correct_answer": ["TRUE", "FALSE", "NOT GIVEN", "TRUE", "FALSE", "TRUE", "NOT GIVEN"][i-1], "academic_explanation": f"Giải thích câu {i} theo văn bản.", "paragraph_ref": "A" if i <= 4 else "B"})
    for i in range(8, 14):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p1, "question_number": i, "type": "summary_completion", "group_header": "Questions 8–13", "group_instruction": "Choose ONE WORD ONLY.", "prompt": f"Concept [ {i} ] …………… highlighted in the passage.", "correct_answer": ["play", "peer", "child", "camera", "intelligence", "rat"][i-8], "academic_explanation": f"Từ khóa câu {i}.", "paragraph_ref": "B"})

    p2 = p_list[1]['id']
    for i in range(14, 21):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p2, "question_number": i, "type": "matching_info", "group_header": "Questions 14–20", "group_instruction": "Which section contains the following information?", "prompt": f"Technical item {i} regarding {p_list[1]['title']}.", "correct_answer": ["A", "B", "A", "B", "A", "B", "A"][i-14], "academic_explanation": f"Dẫn chứng đoạn văn mục {i}.", "paragraph_ref": "A" if i % 2 == 0 else "B"})
    for i in range(21, 27):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p2, "question_number": i, "type": "summary_completion", "group_header": "Questions 21–26", "group_instruction": "Choose ONE WORD ONLY.", "prompt": f"Key mechanism [ {i} ] …………… identified by researchers.", "correct_answer": ["bike", "dock", "screen", "playground", "insect", "zoo"][i-21], "academic_explanation": f"Từ khóa câu {i}.", "paragraph_ref": "B"})

    p3 = p_list[2]['id']
    for i in range(27, 35):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p3, "question_number": i, "type": "multiple_choice", "group_header": "Questions 27–34", "group_instruction": "Choose the correct letter, A, B, C or D.", "prompt": f"Theoretical deduction {i} in {p_list[2]['title']}?", "options": ["A", "B", "C", "D"], "correct_answer": ["C", "B", "A", "D", "B", "A", "C", "D"][i-27], "academic_explanation": f"Phân tích học thuật câu {i}.", "paragraph_ref": "B"})
    for i in range(35, 41):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p3, "question_number": i, "type": "tfng", "group_header": "Questions 35–40", "group_instruction": "Write YES, NO, or NOT GIVEN.", "prompt": f"Claim {i} matches scholarly consensus.", "options": ["YES", "NO", "NOT GIVEN"], "correct_answer": ["YES", "NO", "NOT GIVEN", "YES", "NO", "YES"][i-35], "academic_explanation": f"Dẫn chứng luận điểm câu {i}.", "paragraph_ref": "B"})
    return q_out

for t_num in range(1, 5):
    p_list = tests_data[t_num]
    q_list = generate_q_set(p_list, 14, t_num)
    make_test(14, t_num, p_list, q_list)
