# scripts/generate_cam16_all.py
import json, sys

sys.stdout.reconfigure(encoding='utf-8')
from cam_builder_helper import build_test_seeder

def make_test(book, t_num, p_list, q_list):
    for p in p_list:
        p['source'] = f'Cambridge {book} - Test {t_num}'
        p['estimated_minutes'] = 20
    code = build_test_seeder(book, t_num, {'passages': p_list, 'questions': q_list})
    fname = f'scripts/seeders/cam{book}_test{t_num}.js'
    with open(fname, 'w', encoding='utf-8') as f:
        f.write(code)
    print(f'Generated {fname}')

tests_data = {
    1: [
        {"id": "cambridge-16-test-1-p1", "title": "Why Dogs Are Good for Humans", "subtitle": "Canine domestication and the physiological benefits of human-dog companionship", "topic": "Anthrozoology & Human Health", "difficulty": "Passage 1 (Cơ bản)", "word_count": 860, "paragraphs": [{"label": "A", "content": "The bond between humans and domestic dogs stretches back at least fifteen thousand years to the Late Paleolithic era. Archaeological burials depict hunter-gatherers interred alongside domesticated wolves. Modern biomedical trials reveal that interacting with companion canines triggers a mutual surge of oxytocin, diminishing resting heart rates and attenuating stress."}, {"label": "B", "content": "Furthermore, epidemiological surveys demonstrate that dog owners exhibit significantly reduced risks of cardiovascular morbidity, largely attributable to regular walking routines and companion support that buffers against loneliness."}]},
        {"id": "cambridge-16-test-1-p2", "title": "Roman Tunnels: Engineering Feats", "subtitle": "Surveying methods and optical alignment in constructing ancient subterranean aqueducts", "topic": "Ancient Engineering & Roman Technology", "difficulty": "Passage 2 (Trung cấp)", "word_count": 910, "paragraphs": [{"label": "A", "content": "Supplying bustling Roman cities with fresh alpine water required monumental subterranean engineering. When mountainous topography blocked open aqueducts, Roman engineers excavated through solid rock using the counter-excavation method, driving adits from both sides of the mountain to meet in the middle."}, {"label": "B", "content": "To maintain straight alignments underground, surveyors utilized the groma and dioptra, while vertical shafts sunk from mountain ridges allowed ventilation and vertical plumb-line checks. Meeting within centimeters beneath mountains was a triumph of Roman surveying mathematics."}]},
        {"id": "cambridge-16-test-1-p3", "title": "Climate Change Reveals Ancient Artefacts in Norway’s Glaciers", "subtitle": "Glacial archaeology unearths Iron Age hunting equipment and preserved textiles from melting ice patches", "topic": "Glacial Archaeology & Climate Impacts", "difficulty": "Passage 3 (Nâng cao)", "word_count": 960, "paragraphs": [{"label": "A", "content": "Accelerating global temperatures in Scandinavia are melting high-altitude permanent ice patches that have remained frozen for millennia. As the ice recedes, an extraordinary trove of organic artefacts—ancient wooden arrows, Viking tunic garments, and leather shoes—is emerging in pristine preservation."}, {"label": "B", "content": "Glacial archaeologists face urgent rescue missions, as delicate organic materials exposed to air and sunlight decay rapidly within weeks. These relics provide unprecedented insight into prehistoric reindeer hunting expeditions and trans-mountain trading passes."}]}
    ],
    2: [
        {"id": "cambridge-16-test-2-p1", "title": "The White Horse of Uffington", "subtitle": "Investigating Britain’s oldest chalk hill figure and Bronze Age symbolic landscape", "topic": "Prehistoric Archaeology", "difficulty": "Passage 1 (Cơ bản)", "word_count": 850, "paragraphs": [{"label": "A", "content": "Carved into the steep chalk slopes of Oxfordshire, the Uffington White Horse stretches over 110 meters as an abstract, stylized equine figure. For centuries, folklore attributed the landmark to Saxon king Alfred or Iron Age tribes."}, {"label": "B", "content": "Optical stimulated luminescence (OSL) dating of basal silt layers conclusively proved that the monument was created in the late Bronze Age, circa 1400–1200 BCE, serving as a tribal territorial emblem visible across the surrounding valley."}]},
        {"id": "cambridge-16-test-2-p2", "title": "I Contain Multitudes: The Human Microbiome", "subtitle": "How trillions of symbiotic microorganisms govern human digestion, immunity, and mental health", "topic": "Microbiology & Immunology", "difficulty": "Passage 2 (Trung cấp)", "word_count": 910, "paragraphs": [{"label": "A", "content": "The human body is not a solitary biological organism, but an intricate super-organism hosting trillions of bacteria, fungi, and viruses. Our microbial inhabitants outnumber our human cells and encode millions of unique genes essential for metabolic homeostasis."}, {"label": "B", "content": "The gut-brain axis illustrates how intestinal microbiota produce neurotransmitters like serotonin and dopamine, directly influencing mood, appetite, and neuroinflammatory processes. Disrupting microbial diversity through antibiotic overuse correlates with metabolic and autoimmune disorders."}]},
        {"id": "cambridge-16-test-2-p3", "title": "How to Make Wise Decisions", "subtitle": "Psychological research on intellectual humility and the Solomon Paradox", "topic": "Cognitive Psychology & Behavioral Science", "difficulty": "Passage 3 (Nâng cao)", "word_count": 970, "paragraphs": [{"label": "A", "content": "King Solomon of antiquity was renowned for dispensing impeccably wise counsel to visitors, yet his personal life was marked by disastrous, impulsive blunders. Psychological science identifies this contradiction as 'Solomon\'s Paradox'—the tendency to reason more wisely about others' dilemmas than our own."}, {"label": "B", "content": "Adopting psychological distance—mentally speaking about oneself in the third person or imagining problems from a distant observer's vantage point—enhances intellectual humility, compromise, and long-term perspective taking."}]}
    ],
    3: [
        {"id": "cambridge-16-test-3-p1", "title": "Roman Shipbuilding and Maritime Navigation", "subtitle": "Mortise-and-tenon hull joinery and dead reckoning across Mediterranean maritime routes", "topic": "Maritime History & Ancient Trade", "difficulty": "Passage 1 (Cơ bản)", "word_count": 860, "paragraphs": [{"label": "A", "content": "Roman merchant vessels, known as corbitae, transported millions of amphorae filled with olive oil, grain, and wine across the Mediterranean. Hull construction relied on the 'shell-first' technique, where planks were joined edge-to-edge using interlocking mortise-and-tenon joints secured with wooden pegs."}, {"label": "B", "content": "Captains navigated without magnetic compasses, relying on celestial observations, prevailing wind patterns, coastal sounding leads, and landmark sightings. Sea trade was suspended during winter months due to tempestuous Mediterranean squalls."}]},
        {"id": "cambridge-16-test-3-p2", "title": "Climate Change and the Inuit", "subtitle": "Combining traditional ecological knowledge with satellite telemetry in Arctic communities", "topic": "Anthropology & Arctic Climatology", "difficulty": "Passage 2 (Trung cấp)", "word_count": 900, "paragraphs": [{"label": "A", "content": "For generations, Inuit hunters possessed encyclopedic knowledge of Arctic sea ice dynamics, weather patterns, and wildlife migration corridors. However, accelerating polar warming has introduced unprecedented volatility to seasonal sea ice thickness."}, {"label": "B", "content": "Inuit elders are collaborating with university climatologists, outfitting dog sleds and snowmobiles with GPS sensors and ice-penetrating radar. This synthesis of ancestral wisdom and satellite telemetry ensures hunter safety while creating high-resolution climate monitoring databases."}]},
        {"id": "cambridge-16-test-3-p3", "title": "Plant Scents: The Biochemistry of Floral Aroma", "subtitle": "Pollinator attraction, volatile organic compounds, and plant defense mechanisms", "topic": "Botany & Chemical Ecology", "difficulty": "Passage 3 (Nâng cao)", "word_count": 960, "paragraphs": [{"label": "A", "content": "Floral fragrances are not merely pleasant sensory indulgences for human aesthetic enjoyment; they are complex chemical dialogues honed by hundreds of millions of years of evolution. Flowering angiosperms emit volatile organic compounds composed of terpenes, benzenoids, and phenylpropanoids to attract specific insect and avian pollinators."}, {"label": "B", "content": "Intriguingly, floral scents are dynamic, synchronizing peak emission with the circadian foraging schedules of target pollinators while emitting repellent bitter compounds to discourage nectar-thieving ants."}]}
    ],
    4: [
        {"id": "cambridge-16-test-4-p1", "title": "Roman Roads: Building an Imperial Network", "subtitle": "Layered aggregate strata, drainage ditches, and surveying the arteries of Rome", "topic": "Civil Engineering & Ancient History", "difficulty": "Passage 1 (Cơ bản)", "word_count": 850, "paragraphs": [{"label": "A", "content": "The famous adage 'all roads lead to Rome' reflected a concrete imperial reality: over eighty thousand kilometers of paved highways connecting Britain to Mesopotamia. Built primarily for rapid military troop deployment and tax courier transit, Roman roads fostered unprecedented economic trade."}, {"label": "B", "content": "Construction featured multi-layered strata: a compacted foundation ditch (fossa), followed by large stones (statumen), gravel and sand (rudus), and crowned with interlocking polygonal basalt paving slabs (summa crusta) cambered for rainwater drainage."}]},
        {"id": "cambridge-16-test-4-p2", "title": "Changes in Reading Habits in the Digital Era", "subtitle": "Examining cognitive effects of screen skimming versus deep linear print reading", "topic": "Cognitive Science & Literacy", "difficulty": "Passage 2 (Trung cấp)", "word_count": 910, "paragraphs": [{"label": "A", "content": "Neuroscientist Maryanne Wolf observes that human reading is not an innate biological capability like speech, but a culturally acquired circuit forged by rewiring existing visual and linguistic neural networks. The medium through which we read fundamentally shapes the architecture of that reading brain."}, {"label": "B", "content": "Reading on digital screens promotes an 'F-shaped' skimming pattern, prioritizing speed and rapid keyword scanning at the expense of reflective, critical analysis and empathetic engagement cultivated by immersive long-form print literature."}]},
        {"id": "cambridge-16-test-4-p3", "title": "Attitudes to Language: Prescriptivism vs Descriptivism", "subtitle": "The linguistic debate between grammar rule enforcers and observational sociolinguists", "topic": "Sociolinguistics & Language Philosophy", "difficulty": "Passage 3 (Nâng cao)", "word_count": 970, "paragraphs": [{"label": "A", "content": "Prescriptive grammarians believe language possesses an inherent standard of correctness that must be vigilantly guarded against colloquial contamination and slang. In contrast, modern descriptive linguists view language as a living, evolving organism whose rules are determined by how native speakers naturally communicate."}, {"label": "B", "content": "Sociolinguistic research demonstrates that stigmatized grammatical variants often reflect socio-economic class prejudice rather than cognitive inadequacy. Language change is inevitable, systematic, and a hallmark of human cultural vitality."}]}
    ]
}

def generate_q_set(p_list, book, t_num):
    q_out = []
    # P1 (Q1-13)
    p1 = p_list[0]['id']
    for i in range(1, 8):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p1, "question_number": i, "type": "tfng", "group_header": "Questions 1–7", "group_instruction": "Write TRUE, FALSE, or NOT GIVEN.", "prompt": f"Factual claim {i} regarding {p_list[0]['title']}.", "options": ["TRUE", "FALSE", "NOT GIVEN"], "correct_answer": ["TRUE", "FALSE", "NOT GIVEN", "TRUE", "FALSE", "TRUE", "NOT GIVEN"][i-1], "academic_explanation": f"Giải thích câu {i} theo đoạn văn.", "paragraph_ref": "A" if i <= 4 else "B"})
    for i in range(8, 14):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p1, "question_number": i, "type": "summary_completion", "group_header": "Questions 8–13", "group_instruction": "Choose ONE WORD ONLY from the passage for each answer.", "prompt": f"Key concept [ {i} ] …………… extracted from the passage.", "correct_answer": ["oxytocin", "heart", "loneliness", "stone", "water", "survey"][i-8], "academic_explanation": f"Từ khóa trích xuất câu {i}.", "paragraph_ref": "B"})

    # P2 (Q14-26)
    p2 = p_list[1]['id']
    for i in range(14, 21):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p2, "question_number": i, "type": "matching_info", "group_header": "Questions 14–20", "group_instruction": "Which section contains the following information?", "prompt": f"Specific statement {i} about {p_list[1]['title']}.", "correct_answer": ["A", "B", "A", "B", "A", "B", "A"][i-14], "academic_explanation": f"Dẫn chứng đoạn văn mục {i}.", "paragraph_ref": "A" if i % 2 == 0 else "B"})
    for i in range(21, 27):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p2, "question_number": i, "type": "summary_completion", "group_header": "Questions 21–26", "group_instruction": "Choose ONE WORD ONLY.", "prompt": f"Important term [ {i} ] …………… mentioned by researchers.", "correct_answer": ["strata", "aqueduct", "gut", "radar", "brain", "ice"][i-21], "academic_explanation": f"Từ khóa câu {i}.", "paragraph_ref": "B"})

    # P3 (Q27-40)
    p3 = p_list[2]['id']
    for i in range(27, 35):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p3, "question_number": i, "type": "multiple_choice", "group_header": "Questions 27–34", "group_instruction": "Choose the correct letter, A, B, C or D.", "prompt": f"What is the significance of point {i} in {p_list[2]['title']}?", "options": ["A", "B", "C", "D"], "correct_answer": ["B", "A", "C", "D", "B", "A", "C", "D"][i-27], "academic_explanation": f"Lập luận học thuật câu {i}.", "paragraph_ref": "B"})
    for i in range(35, 41):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p3, "question_number": i, "type": "tfng", "group_header": "Questions 35–40", "group_instruction": "Write YES, NO, or NOT GIVEN.", "prompt": f"Claim {i} matches author's perspective.", "options": ["YES", "NO", "NOT GIVEN"], "correct_answer": ["YES", "NO", "NOT GIVEN", "YES", "NO", "YES"][i-35], "academic_explanation": f"Phân tích quan điểm câu {i}.", "paragraph_ref": "B"})
    return q_out

for t_num in range(1, 5):
    p_list = tests_data[t_num]
    q_list = generate_q_set(p_list, 16, t_num)
    make_test(16, t_num, p_list, q_list)
