# scripts/generate_cam20_t4.py
import json, sys

sys.stdout.reconfigure(encoding='utf-8')

with open('scripts/cam20_data.json', 'r', encoding='utf-8') as f:
    cam20 = json.load(f)

from generate_cam20_t1 import make_seeder_code

q_test4 = {
    'p1': [
        {'num': 1, 'type': 'summary_completion', 'header': 'Questions 1–7', 'inst': 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', 'prompt': 'studied art, then worked as an art [1] …………… in schools across Virginia and Texas.', 'ans': 'teacher', 'ref': 'A', 'exp': 'Đoạn A: "She financed her independent painting by working as an elementary art teacher across rural schools".'},
        {'num': 2, 'type': 'summary_completion', 'header': 'Questions 1–7', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'produced breakthrough abstract drawings using black [2] …………… on paper.', 'ans': 'charcoal', 'ref': 'B', 'exp': 'Đoạn B: "In 1915, O\'Keeffe executed a revolutionary series of abstract charcoal drawings expressing pure emotion".'},
        {'num': 3, 'type': 'summary_completion', 'header': 'Questions 1–7', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'painted towering New York [3] …………… celebrating modern urban geometry.', 'ans': 'skyscrapers', 'ref': 'C', 'exp': 'Đoạn C: "Her canvases capturing soaring Manhattan skyscrapers established her as a preeminent urban modernist".'},
        {'num': 4, 'type': 'summary_completion', 'header': 'Questions 1–7', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'created monumental close-ups of blooming [4] …………… filling expansive canvases.', 'ans': 'flowers', 'ref': 'D', 'exp': 'Đoạn D: "Magnifying the delicate anatomy of flowers to monumental proportions became her signature motif".'},
        {'num': 5, 'type': 'summary_completion', 'header': 'Questions 1–7', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'collected sun-bleached animal [5] …………… scattered across the New Mexico desert.', 'ans': 'bones', 'ref': 'E', 'exp': 'Đoạn E: "In the arid Southwest, she gathered sun-bleached animal bones and skulls as emblems of desert endurance".'},
        {'num': 6, 'type': 'summary_completion', 'header': 'Questions 1–7', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'captured the austere, vivid red-rock [6] …………… surrounding Ghost Ranch.', 'ans': 'landscape', 'ref': 'F', 'exp': 'Đoạn F: "Her desert landscape compositions celebrated the dramatic cliffs and arid plateaus of northern New Mexico".'},
        {'num': 7, 'type': 'summary_completion', 'header': 'Questions 1–7', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'viewed winding desert [7] …………… and cloud formations from aircraft windows in later life.', 'ans': 'rivers', 'ref': 'G', 'exp': 'Đoạn G: "Global aerial travels inspired abstract representations of sinuous rivers and cloud banks viewed from above".'},
        {'num': 8, 'type': 'tfng', 'header': 'Questions 8–13', 'inst': 'Do the following statements agree with the information given in Reading Passage 1? Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Georgia O\'Keeffe\'s artistic style was heavily swayed by fleeting European art trends.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'FALSE', 'ref': 'A', 'exp': 'Đoạn A: "Remarkably, she remained independent from shifting art trends and her work stayed true to her individual vision".'},
        {'num': 9, 'type': 'tfng', 'header': 'Questions 8–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Alfred Stieglitz exhibited O\'Keeffe\'s drawings without her advance permission in New York.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'TRUE', 'ref': 'B', 'exp': 'Đoạn B: "Without O\'Keeffe\'s prior knowledge or consent, gallery owner Alfred Stieglitz hung her charcoal works in his 291 Gallery".'},
        {'num': 10, 'type': 'tfng', 'header': 'Questions 8–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Art critics universally praised her flower paintings for their botanical scientific accuracy.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'FALSE', 'ref': 'D', 'exp': 'Đoạn D chỉ ra giới phê bình diễn giải tranh hoa của bà theo hướng ẩn dụ tâm lý học chứ không phải tranh minh họa thực vật học.'},
        {'num': 11, 'type': 'tfng', 'header': 'Questions 8–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'O\'Keeffe permanently relocated to New Mexico following the passing of Alfred Stieglitz.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'TRUE', 'ref': 'E', 'exp': 'Đoạn E: "Following Stieglitz\'s death in 1946, she made New Mexico her permanent, year-round residence".'},
        {'num': 12, 'type': 'tfng', 'header': 'Questions 8–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'She preferred working with oil paint over watercolor throughout her entire artistic career.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'NOT GIVEN', 'ref': 'F', 'exp': 'Bài đọc đề cập việc bà vẽ cả màu dầu và màu nước nhưng không nói bà thích chất liệu nào hơn.'},
        {'num': 13, 'type': 'tfng', 'header': 'Questions 8–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Failing eyesight caused her to cease all creative artistic output during her final decade.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'NOT GIVEN', 'ref': 'G', 'exp': 'Đoạn G ghi nhận thị lực suy giảm nhưng bà vẫn tiếp tục sáng tác đồ gốm và nhờ người hỗ trợ vẽ tranh cho đến cuối đời.'}
    ],
    'p2': [
        {'num': 14, 'type': 'matching_info', 'header': 'Questions 14–17', 'inst': 'Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information?', 'prompt': 'how a type of plant functions as a natural protection for coastlines', 'ans': 'D', 'ref': 'D', 'exp': 'Đoạn D giải thích rừng ngập mặn và rặng dừa ven biển đóng vai trò giảm chấn tự nhiên trước sóng thần và triều cường.'},
        {'num': 15, 'type': 'matching_info', 'header': 'Questions 14–17', 'inst': 'Which paragraph contains the following information?', 'prompt': 'a prediction about how long it could take to stop noticing the effects of climate change', 'ans': 'A', 'ref': 'A', 'exp': 'Đoạn A dự báo rằng ngay cả khi phát thải dừng lại hôm nay, tác động khí hậu vẫn tiếp tục kéo dài nhiều thập kỷ.'},
        {'num': 16, 'type': 'matching_info', 'header': 'Questions 14–17', 'inst': 'Which paragraph contains the following information?', 'prompt': 'reference to houses engineered to adjust their elevation during catastrophic floods', 'ans': 'D', 'ref': 'C', 'exp': 'Đoạn C mô tả kiến trúc lưỡng cư (amphibious houses) với móng tự nổi nâng cao nhà khi nước ngập.'},
        {'num': 17, 'type': 'matching_info', 'header': 'Questions 14–17', 'inst': 'Which paragraph contains the following information?', 'prompt': 'an example of an ancient engineering practice being revived to manage urban runoff', 'ans': 'F', 'ref': 'F', 'exp': 'Đoạn F đề cập đến việc tái sinh hệ thống ao thấm nước cổ xưa tại Ấn Độ để giảm ngập úng đô thị.'},
        {'num': 18, 'type': 'summary_completion', 'header': 'Questions 18–22', 'inst': 'Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.', 'prompt': 'Municipalities install high-capacity industrial [18] …………… to evacuate floodwaters into river estuaries.', 'ans': 'pumps', 'ref': 'B', 'exp': 'Đoạn B: "Coastal cities deploy heavy-duty stormwater pumps to rapidly discharge inundations".'},
        {'num': 19, 'type': 'summary_completion', 'header': 'Questions 18–22', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Constructing massive concrete [19] …………… protects low-lying farmland against tidal intrusion.', 'ans': 'dams', 'ref': 'B', 'exp': 'Đoạn B: "Extensive networks of dikes, sea gates, and concrete dams shield agrarian plains".'},
        {'num': 20, 'type': 'summary_completion', 'header': 'Questions 18–22', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Amphibious foundations are engineered to [20] …………… vertically upon rising flood currents.', 'ans': 'float', 'ref': 'C', 'exp': 'Đoạn C: "Hollow buoyant foundations enable entire residences to float safely above floodwaters".'},
        {'num': 21, 'type': 'summary_completion', 'header': 'Questions 18–22', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Agronomists breed resilient saline-tolerant [21] …………… to sustain rural food security.', 'ans': 'crops', 'ref': 'E', 'exp': 'Đoạn E: "Cultivating salt-resilient food crops ensures agricultural stability as sea levels penetrate aquifers".'},
        {'num': 22, 'type': 'summary_completion', 'header': 'Questions 18–22', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Urban forestry initiatives plant thousands of shade-giving [22] …………… to mitigate urban heat islands.', 'ans': 'trees', 'ref': 'E', 'exp': 'Đoạn E: "Planting canopy trees along asphalt boulevards cools metropolitan centers significantly".'},
        {'num': 23, 'type': 'matching_info', 'header': 'Questions 23–26', 'inst': 'Match each statement with the correct researcher (A: Yanira Pineda, B: Susanna Tol, C: Elizabeth English, D: Mark Saunders, E: Greg Spotts).', 'prompt': 'Advocated combining traditional wetlands restoration with civic infrastructure.', 'ans': 'B', 'ref': 'D', 'exp': 'Bà Susanna Tol nhấn mạnh việc khôi phục đầm lầy tự nhiên kết hợp với công trình nhân tạo.'},
        {'num': 24, 'type': 'matching_info', 'header': 'Questions 23–26', 'inst': 'Match each statement with the correct researcher.', 'prompt': 'Pioneered street-level thermal reflective asphalt coatings in major urban centers.', 'ans': 'E', 'ref': 'E', 'exp': 'Greg Spotts triển khai lớp sơn phản quang hạ nhiệt mặt đường tại Los Angeles.'},
        {'num': 25, 'type': 'matching_info', 'header': 'Questions 23–26', 'inst': 'Match each statement with the correct researcher.', 'prompt': 'Monitored soil moisture sensor arrays in vulnerable high-altitude Andean communities.', 'ans': 'A', 'ref': 'B', 'exp': 'Yanira Pineda lắp đặt hệ thống cảm biến độ ẩm đất ở vùng núi cao để cảnh báo sạt lở.'},
        {'num': 26, 'type': 'matching_info', 'header': 'Questions 23–26', 'inst': 'Match each statement with the correct researcher.', 'prompt': 'Founded the Buoyant Foundation Project to retrofit homes with amphibious foundations.', 'ans': 'C', 'ref': 'C', 'exp': 'Elizabeth English sáng lập dự án nâng cấp nhà ở truyền thống thành nhà phao tự nổi.'}
    ],
    'p3': [
        {'num': 27, 'type': 'matching_info', 'header': 'Questions 27–31', 'inst': 'Reading Passage 3 has seven paragraphs, A–G. Which paragraph contains the following information?', 'prompt': 'an example of how one predator has been protected by the introduction of guardian dogs', 'ans': 'D', 'ref': 'D', 'exp': 'Đoạn D mô tả báo săn cheetah ở Namibia được bảo vệ khỏi bị nông dân bắn hạ nhờ chó canh cừu.'},
        {'num': 28, 'type': 'matching_info', 'header': 'Questions 27–31', 'inst': 'Which paragraph contains the following information?', 'prompt': 'details of the specific bonding process required between puppies and farm livestock', 'ans': 'G', 'ref': 'B', 'exp': 'Đoạn B mô tả quy trình cho chó con sống chung và gắn kết tình cảm với đàn cừu từ khi còn nhỏ.'},
        {'num': 29, 'type': 'matching_info', 'header': 'Questions 27–31', 'inst': 'Which paragraph contains the following information?', 'prompt': 'historical evidence demonstrating that guardian dog lineages date back thousands of years', 'ans': 'B', 'ref': 'A', 'exp': 'Đoạn A dẫn chứng lịch sử: giống chó Anatolian và Maremma đã canh giữ gia súc từ thời Lưỡng Hà cổ đại.'},
        {'num': 30, 'type': 'matching_info', 'header': 'Questions 27–31', 'inst': 'Which paragraph contains the following information?', 'prompt': 'economic calculations showing reductions in livestock predation losses', 'ans': 'C', 'ref': 'C', 'exp': 'Đoạn C trình bày số liệu thống kê: đàn cừu được bảo vệ giảm tỷ lệ thiệt hại do chó sói tới trên 90%.'},
        {'num': 31, 'type': 'matching_info', 'header': 'Questions 27–31', 'inst': 'Which paragraph contains the following information?', 'prompt': 'an explanation of how dog barks and scent marking deter carnivores without lethal conflict', 'ans': 'B', 'ref': 'D', 'exp': 'Đoạn D giải thích chó bảo hộ dùng tiếng sủa cảnh báo và đánh dấu lãnh thổ để xua đuổi thú dữ mà không cần cắn chết chúng.'},
        {'num': 32, 'type': 'matching_info', 'header': 'Questions 32–36', 'inst': 'Match each statement with the correct person (A: Dan Macon, B: Laurie Marker, C: David Macdonald, D: Linda van Bommel, E: Ray Coppinger).', 'prompt': 'Conducted widespread surveys across Australian ranches evaluating Maremma sheepdogs.', 'ans': 'D', 'ref': 'C', 'exp': 'Linda van Bommel khảo sát quy mô lớn trên các nông trại cừu ở Úc.'},
        {'num': 33, 'type': 'matching_info', 'header': 'Questions 32–36', 'inst': 'Match each statement with the correct person.', 'prompt': 'Pioneered behavioral ethology studies on guardian dogs versus herding breeds.', 'ans': 'E', 'ref': 'A', 'exp': 'Ray Coppinger tiên phong nghiên cứu tập tính học phân biệt giữa chó lùa cừu và chó bảo hộ.'},
        {'num': 34, 'type': 'matching_info', 'header': 'Questions 32–36', 'inst': 'Match each statement with the correct person.', 'prompt': 'Established the Cheetah Conservation Fund program pairing Anatolian Shepherds with Namibian farmers.', 'ans': 'B', 'ref': 'D', 'exp': 'Laurie Marker thành lập quỹ bảo tồn báo săn và trao tặng chó chăn cừu cho nông dân Namibia.'},
        {'num': 35, 'type': 'matching_info', 'header': 'Questions 32–36', 'inst': 'Match each statement with the correct person.', 'prompt': 'Emphasized that non-lethal predator deterrence fosters biodiversity conservation.', 'ans': 'C', 'ref': 'E', 'exp': 'David Macdonald khẳng định bảo tồn loài ăn thịt đầu chuỗi bằng biện pháp phi bạo lực là chìa khóa duy trì hệ sinh thái.'},
        {'num': 36, 'type': 'matching_info', 'header': 'Questions 32–36', 'inst': 'Match each statement with the correct person.', 'prompt': 'Stated that managing guardian dogs requires ongoing commitment and proper livestock socialization.', 'ans': 'A', 'ref': 'F', 'exp': 'Dan Macon nhấn mạnh việc nuôi dạy chó bảo vệ đòi hỏi sự kiên nhẫn và gắn kết bầy đàn liên tục.'},
        {'num': 37, 'type': 'summary_completion', 'header': 'Questions 37–40', 'inst': 'Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.', 'prompt': 'Guardian dogs prevent attacks by opportunist predators such as wild [37] …………… in grazing pastures.', 'ans': 'jackals', 'ref': 'C', 'exp': 'Đoạn C: "Deploying guardian dogs dramatically curtailed attacks by wolves, caracals, and jackals".'},
        {'num': 38, 'type': 'summary_completion', 'header': 'Questions 37–40', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Veterinary care is essential to ensure working dogs do not spread infectious [38] …………… to wild carnivores.', 'ans': 'diseases', 'ref': 'E', 'exp': 'Đoạn E: "Routine vaccination prevents domestic working dogs from transmitting canine diseases to endangered wild predators".'},
        {'num': 39, 'type': 'summary_completion', 'header': 'Questions 37–40', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Farmers must supply adequate [39] …………… so dogs do not abandon their post to scavenge.', 'ans': 'food', 'ref': 'F', 'exp': 'Đoạn F: "Providing sufficient nutritional food ensures the dogs remain loyal to the livestock herd rather than wandering".'},
        {'num': 40, 'type': 'summary_completion', 'header': 'Questions 37–40', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'On small islands, guardian dogs successfully deter predatory [40] …………… from invading seabird breeding colonies.', 'ans': 'foxes', 'ref': 'G', 'exp': 'Đoạn G: "On Middle Island, Maremma dogs successfully protected little penguin rookeries from introduced red foxes".'}
    ]
}

print('Writing Cambridge 20 Test 4 seeder...')
t4_code = make_seeder_code(4, cam20['4'], q_test4)
with open('scripts/seeders/cam20_test4.js', 'w', encoding='utf-8') as f:
    f.write(t4_code)

print('cam20_test4.js generated successfully!')
