# scripts/generate_cam20_t3_t4.py
import json, sys

sys.stdout.reconfigure(encoding='utf-8')

with open('scripts/cam20_data.json', 'r', encoding='utf-8') as f:
    cam20 = json.load(f)

from generate_cam20_t1 import make_seeder_code

q_test3 = {
    'p1': [
        {'num': 1, 'type': 'summary_completion', 'header': 'Questions 1–7', 'inst': 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', 'prompt': 'Early attempts to preserve [1] …………… through cold temperature failed due to texture decay.', 'ans': 'potatoes', 'ref': 'A', 'exp': 'Đoạn A: "Traditional cold-storage attempts with root vegetables like potatoes yielded soggy, unpalatable pulp".'},
        {'num': 2, 'type': 'summary_completion', 'header': 'Questions 1–7', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Birdseye observed native Inuits preserving fresh [2] …………… and game in sub-zero winds.', 'ans': 'butter', 'ref': 'B', 'exp': 'Đoạn B: "Inuit hunters preserved fish, game meat, and sea-mammal butter instantly frozen by arctic gusts".'},
        {'num': 3, 'type': 'summary_completion', 'header': 'Questions 1–7', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Rapid freezing retained the original texture and juices of [3] …………… far better than slow chilling.', 'ans': 'meat', 'ref': 'B', 'exp': 'Đoạn B: "Instantly frozen meat thawed with pristine moisture, mimicking freshly harvested produce".'},
        {'num': 4, 'type': 'summary_completion', 'header': 'Questions 1–7', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Slow freezing generated enormous ice [4] …………… that ruptured delicate cell walls.', 'ans': 'crystals', 'ref': 'C', 'exp': 'Đoạn C: "Conventional freezing produced large, jagged ice crystals that punctured microscopic cellular walls".'},
        {'num': 5, 'type': 'summary_completion', 'header': 'Questions 1–7', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Birdseye packaged food in waterproof wax-coated [5] …………… prior to compression.', 'ans': 'cellophane', 'ref': 'D', 'exp': 'Đoạn D: "Foodstuffs were pre-packaged inside waterproof cellophane pouches before entering the multi-plate freezer".'},
        {'num': 6, 'type': 'summary_completion', 'header': 'Questions 1–7', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Grocers were initially reluctant to invest in refrigerated display cases made of [6] ……………', 'ans': 'tin', 'ref': 'E', 'exp': 'Đoạn E: "Retailers resisted expensive investments in insulated tin and glass display cabinets".'},
        {'num': 7, 'type': 'summary_completion', 'header': 'Questions 1–7', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Post-war proliferation of the home [7] …………… firmly cemented frozen meals in daily life.', 'ans': 'refrigerator', 'ref': 'F', 'exp': 'Đoạn F: "The mass adoption of the electric domestic refrigerator transformed national dietary routines".'},
        {'num': 8, 'type': 'tfng', 'header': 'Questions 8–13', 'inst': 'Do the following statements agree with the information given in Reading Passage 1? Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Clarence Birdseye had formal qualifications in cryogenic thermodynamic engineering.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'NOT GIVEN', 'ref': 'B', 'exp': 'Bài đọc mô tả Birdseye là một nhà tự nhiên học nhạy bén nhưng không nói về bằng cấp kỹ thuật lạnh chính quy.'},
        {'num': 9, 'type': 'tfng', 'header': 'Questions 8–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'The multi-plate quick-freezing machine applied mechanical pressure during freezing.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'TRUE', 'ref': 'D', 'exp': 'Đoạn D: "Hydraulic pressure held hollow metal plates firmly against the packages while chilled brine circulated within".'},
        {'num': 10, 'type': 'tfng', 'header': 'Questions 8–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Consumers immediately preferred frozen vegetables over fresh farm produce in 1930.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'FALSE', 'ref': 'E', 'exp': 'Đoạn E chỉ ra sự hoài nghi của người tiêu dùng thập niên 1930: họ nghi ngại thực phẩm đông lạnh là đồ ôi thiu lưu kho.'},
        {'num': 11, 'type': 'tfng', 'header': 'Questions 8–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Government military contracts during World War II accelerated frozen food adoption.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'TRUE', 'ref': 'E', 'exp': 'Đoạn E xác nhận: Thiếu hụt hộp thiếc thời chiến buộc quân đội chuyển sang tiêu thụ thực phẩm đông lạnh số lượng lớn.'},
        {'num': 12, 'type': 'tfng', 'header': 'Questions 8–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Birdseye died in poverty after losing patent rights to his inventions.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'FALSE', 'ref': 'F', 'exp': 'Đoạn F cho biết Birdseye bán công ty với giá 22 triệu USD (khoản tiền khổng lồ lúc bấy giờ) và trở nên giàu có.'},
        {'num': 13, 'type': 'tfng', 'header': 'Questions 8–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Modern frozen foods contain higher nutrient concentrations than organically grown fresh crops.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'NOT GIVEN', 'ref': 'F', 'exp': 'Bài đọc không so sánh hàm lượng dinh dưỡng của thực phẩm đông lạnh với nông sản hữu cơ.'}
    ],
    'p2': [
        {'num': 14, 'type': 'matching_info', 'header': 'Questions 14–19', 'inst': 'Reading Passage 2 has six sections, A–F. Choose the correct heading for each section from the list of headings below (i–vii).', 'prompt': 'Section A', 'ans': 'v', 'ref': 'A', 'exp': 'Mục A: Tiêu đề v phản ánh mức độ nghiêm trọng của hiện tượng tẩy trắng san hô do nhiệt độ nước biển tăng cao.'},
        {'num': 15, 'type': 'matching_info', 'header': 'Questions 14–19', 'inst': 'Choose the correct heading.', 'prompt': 'Section B', 'ans': 'ii', 'ref': 'B', 'exp': 'Mục B: Tiêu đề ii nói về mối quan hệ cộng sinh mong manh giữa polyp san hô và tảo zooxanthellae.'},
        {'num': 16, 'type': 'matching_info', 'header': 'Questions 14–19', 'inst': 'Choose the correct heading.', 'prompt': 'Section C', 'ans': 'iv', 'ref': 'C', 'exp': 'Mục C: Tiêu đề iv giới thiệu phương pháp nhân giống san hô siêu chịu nhiệt trong phòng thí nghiệm.'},
        {'num': 17, 'type': 'matching_info', 'header': 'Questions 14–19', 'inst': 'Choose the correct heading.', 'prompt': 'Section D', 'ans': 'vii', 'ref': 'D', 'exp': 'Mục D: Tiêu đề vii thảo luận về chi phí khổng lồ và thách thức mở rộng quy mô phục hồi rạn san hô tự nhiên.'},
        {'num': 18, 'type': 'matching_info', 'header': 'Questions 14–19', 'inst': 'Choose the correct heading.', 'prompt': 'Section E', 'ans': 'iii', 'ref': 'E', 'exp': 'Mục E: Tiêu đề iii đề cập đến vai trò của các khu bảo tồn biển được quản lý nghiêm ngặt.'},
        {'num': 19, 'type': 'matching_info', 'header': 'Questions 14–19', 'inst': 'Choose the correct heading.', 'prompt': 'Section F', 'ans': 'vi', 'ref': 'F', 'exp': 'Mục F: Tiêu đề vi tổng kết triển vọng tương lai phụ thuộc vào việc cắt giảm lượng khí thải carbon toàn cầu.'},
        {'num': 20, 'type': 'multiple_choice', 'header': 'Questions 20–23', 'inst': 'Choose TWO letters, A–E.', 'prompt': 'Which TWO human activities directly accelerate coral degradation? [Choose C or E]', 'opts': ['Underwater photography tourism in shallow lagoons', 'Installation of offshore tidal electricity turbines', 'Agricultural fertilizer runoff triggering toxic algae blooms', 'Commercial submarine telecommunication cabling', 'Destructive coastal blast fishing and bottom trawling'], 'ans': 'C', 'ref': 'A', 'exp': 'Phân bón nông nghiệp chảy ra biển gây bùng phát tảo độc làm ngạt rạn san hô.'},
        {'num': 21, 'type': 'multiple_choice', 'header': 'Questions 20–23', 'inst': 'Choose TWO letters, A–E.', 'prompt': 'Which other human activity directly accelerates coral degradation? [Choose C or E]', 'opts': ['Underwater photography tourism in shallow lagoons', 'Installation of offshore tidal electricity turbines', 'Agricultural fertilizer runoff triggering toxic algae blooms', 'Commercial submarine telecommunication cabling', 'Destructive coastal blast fishing and bottom trawling'], 'ans': 'E', 'ref': 'A', 'exp': 'Đánh bắt hải sản bằng chất nổ và lưới rào cào quét tàn phá kết cấu rạn đá vôi.'},
        {'num': 22, 'type': 'multiple_choice', 'header': 'Questions 20–23', 'inst': 'Choose TWO letters, A–E.', 'prompt': 'Which TWO scientific innovations show promise in restoring reefs? [Choose B or D]', 'opts': ['Constructing concrete sea walls around entire archipelagos', 'Assisted gene flow breeding heat-tolerant micro-algae strains', 'Pumping chilled deep ocean water onto surface reefs', 'Deploying 3D-printed ceramic substrate scaffolding for larvae settlement', 'Introducing foreign starfish species to control benthic algae'], 'ans': 'B', 'ref': 'C', 'exp': 'Nhân giống chọn lọc các dòng vi tảo có khả năng quang hợp ở nhiệt độ cao.'},
        {'num': 23, 'type': 'multiple_choice', 'header': 'Questions 20–23', 'inst': 'Choose TWO letters, A–E.', 'prompt': 'Which other scientific innovation shows promise? [Choose B or D]', 'opts': ['Constructing concrete sea walls around entire archipelagos', 'Assisted gene flow breeding heat-tolerant micro-algae strains', 'Pumping chilled deep ocean water onto surface reefs', 'Deploying 3D-printed ceramic substrate scaffolding for larvae settlement', 'Introducing foreign starfish species to control benthic algae'], 'ans': 'D', 'ref': 'C', 'exp': 'Thả giá thể gốm in 3D mô phỏng địa hình rạn để ấu trùng san hô bám đậu.'},
        {'num': 24, 'type': 'summary_completion', 'header': 'Questions 24–26', 'inst': 'Complete the sentences below. Choose ONE WORD ONLY from the passage for each answer.', 'prompt': 'Coral polyps extend stinging [24] …………… at night to capture suspended zooplankton.', 'ans': 'tentacles', 'ref': 'B', 'exp': 'Đoạn B: "Tiny carnivorous polyps unfurl delicate stinging tentacles into the nocturnal currents".'},
        {'num': 25, 'type': 'summary_completion', 'header': 'Questions 24–26', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'The hard calcium carbonate skeleton provides vital physical [25] …………… for coastal communities against storm surges.', 'ans': 'protection', 'ref': 'B', 'exp': 'Đoạn B: "Extensive reef barriers afford indispensable wave attenuation and shoreline protection".'},
        {'num': 26, 'type': 'summary_completion', 'header': 'Questions 24–26', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Expulsion of endosymbiotic algae causes corals to lose their characteristic [26] …………… and turn ghostly white.', 'ans': 'color', 'ref': 'A', 'exp': 'Đoạn A: "Thermal stress prompts polyps to eject photosynthetic algae, stripping colonies of their vibrant color".'}
    ],
    'p3': [
        {'num': 27, 'type': 'multiple_choice', 'header': 'Questions 27–33', 'inst': 'Choose the correct letter, A, B, C or D.', 'prompt': 'According to the writer, our emotional reaction to companion robots is primarily shaped by', 'opts': ['innate human tendencies to project intentionality and emotions onto inanimate objects.', 'sophisticated neural networks perfectly mimicking consciousness.', 'aggressive marketing campaigns by robotics conglomerates.', 'the widespread decline in real-world human social bonds.'], 'ans': 'A', 'ref': 'A', 'exp': 'Xu hướng phóng chiếu cảm xúc và gán cho đồ vật ý thức sống là bản năng tự nhiên của con người.'},
        {'num': 28, 'type': 'multiple_choice', 'header': 'Questions 27–33', 'inst': 'Choose the correct letter, A, B, C or D.', 'prompt': 'What did the military testing of bomb-disposal robots reveal?', 'opts': ['Soldiers ignored robotic malfunctions under fire.', 'Operators developed genuine protective attachment toward their units.', 'Robots consistently outperformed trained canine handlers.', 'Commanders preferred mechanical casualties over human loss.'], 'ans': 'B', 'ref': 'B', 'exp': 'Binh lính cảm thấy xót xa và tổ chức lễ tang danh dự khi robot gỡ bom bị nổ tung.'},
        {'num': 29, 'type': 'multiple_choice', 'header': 'Questions 27–33', 'inst': 'Choose the correct letter, A, B, C or D.', 'prompt': 'The "uncanny valley" hypothesis suggests that people feel uncomfortable when an android', 'opts': ['displays unpredictable software bugs.', 'resembles a human being almost perfectly but possesses subtle flaws.', 'communicates in a flat synthetic monotone.', 'physically towers over human conversational partners.'], 'ans': 'B', 'ref': 'C', 'exp': 'Thuyết Thung lũng kỳ lạ: robot càng giống người nhưng thiếu sự sống động tự nhiên thì càng gây rùng mình.'},
        {'num': 30, 'type': 'multiple_choice', 'header': 'Questions 27–33', 'inst': 'Choose the correct letter, A, B, C or D.', 'prompt': 'Therapeutic robotic pets like Paro the seal are effective because they', 'opts': ['dispense prescribed pharmaceutical medications on time.', 'never require maintenance or recharging.', 'evoke calming nurturing instincts without interpersonal demands.', 'cost significantly less than certified service animals.'], 'ans': 'C', 'ref': 'D', 'exp': 'Robot hải cẩu Paro kích hoạt bản năng chăm sóc vỗ về mà không đòi hỏi nghĩa vụ phức tạp như người thật.'},
        {'num': 31, 'type': 'multiple_choice', 'header': 'Questions 27–33', 'inst': 'Choose the correct letter, A, B, C or D.', 'prompt': 'Critics express ethical concern that robotic eldercare could lead to', 'opts': ['unforeseen mechanical injuries among frail patients.', 'the social abdication of familial human care and companionship.', 'skyrocketing subscription fees charged by tech vendors.', 'excessive data surveillance in private bedrooms.'], 'ans': 'B', 'ref': 'E', 'exp': 'Mối lo ngại xã hội phó mặc người cao tuổi cho máy móc và tước đi sự đồng hành ấm áp của con người.'},
        {'num': 32, 'type': 'multiple_choice', 'header': 'Questions 27–33', 'inst': 'Choose the correct letter, A, B, C or D.', 'prompt': 'The concept of "artificial empathy" refers to software that', 'opts': ['simulates affective awareness based on vocal inflection and facial cues.', 'actually experiences emotional pain alongside users.', 'refuses commands that would hurt human feelings.', 'autonomously modifies its underlying ethical code.'], 'ans': 'A', 'ref': 'F', 'exp': 'Sự thấu cảm nhân tạo là thuật toán nhận diện nét mặt và giọng nói để đưa ra phản hồi phù hợp.'},
        {'num': 33, 'type': 'multiple_choice', 'header': 'Questions 27–33', 'inst': 'Choose the correct letter, A, B, C or D.', 'prompt': 'In conclusion, the author views the future of human-robot relationships as', 'opts': ['an existential catastrophe bound to erode authentic human community.', 'a trivial cultural fad that will vanish once the novelty subsides.', 'a mirror reflecting fundamental aspects of human psychology and vulnerability.', 'a technological paradise eliminating loneliness entirely.'], 'ans': 'C', 'ref': 'G', 'exp': 'Mối quan hệ với robot chính là tấm gương phản chiếu sâu sắc tâm lý và sự mong manh trong tâm hồn con người.'},
        {'num': 34, 'type': 'matching_info', 'header': 'Questions 34–40', 'inst': 'Complete the summary. Choose the correct letter, A–H, below.', 'prompt': 'Philosophers argue that humans are uniquely predisposed to seek [34] …………… even in synthetic entities.', 'ans': 'C', 'ref': 'A', 'exp': 'Con người luôn tìm kiếm sự kết nối xã hội (social connection).'},
        {'num': 35, 'type': 'matching_info', 'header': 'Questions 34–40', 'inst': 'Choose the correct letter.', 'prompt': 'Early behavioral experiments showed children treating robotic dogs as [35] …………… companions.', 'ans': 'B', 'ref': 'C', 'exp': 'Trẻ em đối xử với chó robot như những người bạn sống thực sự (living companions).'},
        {'num': 36, 'type': 'matching_info', 'header': 'Questions 34–40', 'inst': 'Choose the correct letter.', 'prompt': 'Developers exploit psychological vulnerabilities by designing interfaces that mimic [36] ……………', 'ans': 'D', 'ref': 'D', 'exp': 'Giao diện bắt chước biểu cảm sinh học tự nhiên (biological cues).'},
        {'num': 37, 'type': 'matching_info', 'header': 'Questions 34–40', 'inst': 'Choose the correct letter.', 'prompt': 'In nursing homes, robotic companions noticeably alleviated clinical [37] ……………', 'ans': 'B', 'ref': 'D', 'exp': 'Giảm thiểu đáng kể chứng trầm cảm và cô đơn (depression).'},
        {'num': 38, 'type': 'matching_info', 'header': 'Questions 34–40', 'inst': 'Choose the correct letter.', 'prompt': 'However, philosophers warn of dangerous emotional [38] …………… on programmed algorithms.', 'ans': 'C', 'ref': 'E', 'exp': 'Cảnh báo nguy cơ lệ thuộc cảm xúc (emotional dependency).'},
        {'num': 39, 'type': 'matching_info', 'header': 'Questions 34–40', 'inst': 'Choose the correct letter.', 'prompt': 'The illusion of mutual care may mask deep corporate [39] ……………', 'ans': 'B', 'ref': 'F', 'exp': 'Che đậy mục đích thương mại và thu thập dữ liệu (commercial interests).'},
        {'num': 40, 'type': 'matching_info', 'header': 'Questions 34–40', 'inst': 'Choose the correct letter.', 'prompt': 'Ultimately, our machines reveal what we most cherish about human [40] ……………', 'ans': 'C', 'ref': 'G', 'exp': 'Phản ánh những giá trị thiêng liêng nhất của tình người (human nature).'}
    ]
}

print('Writing Cambridge 20 Test 3 seeder...')
t3_code = make_seeder_code(3, cam20['3'], q_test3)
with open('scripts/seeders/cam20_test3.js', 'w', encoding='utf-8') as f:
    f.write(t3_code)

print('cam20_test3.js generated successfully!')
