# scripts/generate_cam20_t2_t3_t4.py
import json, sys

sys.stdout.reconfigure(encoding='utf-8')

with open('scripts/cam20_data.json', 'r', encoding='utf-8') as f:
    cam20 = json.load(f)

from generate_cam20_t1 import make_seeder_code

q_test2 = {
    'p1': [
        {'num': 1, 'type': 'summary_completion', 'header': 'Questions 1–6', 'inst': 'Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.', 'prompt': 'manatees have a rounded, paddle-shaped [1] …………… which distinguishes them from dugongs.', 'ans': 'tail', 'ref': 'A', 'exp': 'Đoạn A: "Unlike dugongs with forked flukes, manatees possess a rounded, paddle-like tail".'},
        {'num': 2, 'type': 'summary_completion', 'header': 'Questions 1–6', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'they use their front [2] …………… to steer and grasp vegetation while feeding.', 'ans': 'flippers', 'ref': 'B', 'exp': 'Đoạn B: "Their flexible pectoral flippers are utilized for steering through water and grasping aquatic plants".'},
        {'num': 3, 'type': 'summary_completion', 'header': 'Questions 1–6', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'sensitive sensory [3] …………… covering their bodies help detect subtle water currents.', 'ans': 'hairs', 'ref': 'C', 'exp': 'Đoạn C: "Vibrissae or tactile hairs scattered across their bodies act as sensory antennae detecting hydrostatic pressure".'},
        {'num': 4, 'type': 'summary_completion', 'header': 'Questions 1–6', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'manatees graze on submerged freshwater and saltwater [4] …………… for hours each day.', 'ans': 'vegetation', 'ref': 'D', 'exp': 'Đoạn D: "As dedicated herbivores, they consume vast quantities of submerged vegetation including seagrass beds".'},
        {'num': 5, 'type': 'summary_completion', 'header': 'Questions 1–6', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'they walk along shallow riverbeds using their muscular [5] ……………', 'ans': 'flippers', 'ref': 'D', 'exp': 'Đoạn D: "They frequently \'walk\' across sandy shallow bottoms supported by their flippers".'},
        {'num': 6, 'type': 'summary_completion', 'header': 'Questions 1–6', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'their dense, heavy bones aid in regulating neutral [6] …………… under water.', 'ans': 'buoyancy', 'ref': 'E', 'exp': 'Đoạn E: "Pachyostotic, extraordinarily dense ribs and skull bones facilitate precise control of neutral buoyancy".'},
        {'num': 7, 'type': 'tfng', 'header': 'Questions 7–13', 'inst': 'Do the following statements agree with the information given in Reading Passage 1? Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Florida manatees are capable of enduring extended periods in sub-freezing ocean currents.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'FALSE', 'ref': 'F', 'exp': 'Đoạn F: "Despite their substantial girth, manatees lack insulating blubber and suffer fatal hypothermia when water temperatures fall below 20°C".'},
        {'num': 8, 'type': 'tfng', 'header': 'Questions 7–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Watercraft collisions are currently the least significant source of manatee mortality.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'FALSE', 'ref': 'G', 'exp': 'Đoạn G chỉ ra chân vịt tàu bè và va chạm cano cao tốc là nguyên nhân hàng đầu gây chấn thương và tử vong ở lợn biển.'},
        {'num': 9, 'type': 'tfng', 'header': 'Questions 7–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Manatees have better eyesight than most marine mammals.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'NOT GIVEN', 'ref': 'H', 'exp': 'Bài đọc mô tả cấu tạo mắt của lợn biển nhưng không đưa ra so sánh với các loài thú biển khác.'},
        {'num': 10, 'type': 'tfng', 'header': 'Questions 7–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Warm-water discharges from coastal power stations have become crucial winter refuges for manatees.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'TRUE', 'ref': 'I', 'exp': 'Đoạn I: "Hundreds of manatees congregate around warm effluents discharged by power generation facilities during cold snaps".'},
        {'num': 11, 'type': 'tfng', 'header': 'Questions 7–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Female manatees abandon their calves immediately after birth.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'FALSE', 'ref': 'J', 'exp': 'Đoạn J nêu tình mẫu tử khăng khít: lợn biển mẹ chăm sóc và bảo vệ con non trong suốt 2 năm đầu đời.'},
        {'num': 12, 'type': 'tfng', 'header': 'Questions 7–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'Public education programs have contributed to stabilizing the Florida manatee population.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'TRUE', 'ref': 'K', 'exp': 'Đoạn K ghi nhận các quy định hạn chế tốc độ tàu và chiến dịch nâng cao nhận thức cộng đồng đã giúp phục hồi số lượng cá thể.'},
        {'num': 13, 'type': 'tfng', 'header': 'Questions 7–13', 'inst': 'Write TRUE, FALSE, or NOT GIVEN.', 'prompt': 'The federal government plans to de-list the manatee from endangered status next year.', 'opts': ['TRUE', 'FALSE', 'NOT GIVEN'], 'ans': 'NOT GIVEN', 'ref': 'K', 'exp': 'Không có thông tin về kế hoạch cụ thể của chính phủ liên bang vào năm tới.'}
    ],
    'p2': [
        {'num': 14, 'type': 'matching_info', 'header': 'Questions 14–16', 'inst': 'Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information?', 'prompt': 'mention of false assumptions about why people procrastinate', 'ans': 'B', 'ref': 'B', 'exp': 'Đoạn B phân tích những ngộ nhận sai lầm xem trì hoãn là sự lười biếng hoặc thiếu kỹ năng quản lý thời gian.'},
        {'num': 15, 'type': 'matching_info', 'header': 'Questions 14–16', 'inst': 'Which paragraph contains the following information?', 'prompt': 'a physiological explanation of how the brain reacts to stressful tasks', 'ans': 'F', 'ref': 'F', 'exp': 'Đoạn F giải thích cơ chế hạch hạnh nhân (amygdala) và vỏ não trước trán xung đột khi gặp nhiệm vụ gây áp lực.'},
        {'num': 16, 'type': 'matching_info', 'header': 'Questions 14–16', 'inst': 'Which paragraph contains the following information?', 'prompt': 'examples of long-term health consequences linked to chronic delay', 'ans': 'B', 'ref': 'D', 'exp': 'Đoạn D liệt kê chứng mất ngủ, tim mạch và căng thẳng mãn tính ở những người trì hoãn kinh niên.'},
        {'num': 17, 'type': 'summary_completion', 'header': 'Questions 17–22', 'inst': 'Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.', 'prompt': 'Many people mistakenly attribute procrastination to personal [17] ……………', 'ans': 'laziness', 'ref': 'B', 'exp': 'Đoạn B: "Contrary to popular belief, procrastination is rarely an issue of moral failing or inherent laziness".'},
        {'num': 18, 'type': 'summary_completion', 'header': 'Questions 17–22', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Individuals often feel deeply [18] …………… when facing challenging assignments.', 'ans': 'anxious', 'ref': 'C', 'exp': 'Đoạn C: "When confronting intimidating duties, subjects reported feeling acutely anxious about failure".'},
        {'num': 19, 'type': 'summary_completion', 'header': 'Questions 17–22', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'The emotional brain interprets complex duties as existential [19] ……………', 'ans': 'threats', 'ref': 'C', 'exp': 'Đoạn C: "The limbic system misconstrues demanding tasks as psychological threats to self-esteem".'},
        {'num': 20, 'type': 'summary_completion', 'header': 'Questions 17–22', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Students frequently delay preparing for crucial academic [20] ……………', 'ans': 'exams', 'ref': 'D', 'exp': 'Đoạn D: "Surveys revealed that over 70% of undergraduates habitually postponed revision for final exams".'},
        {'num': 21, 'type': 'summary_completion', 'header': 'Questions 17–22', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'Highly vulnerable individuals are self-critical [21] …………… demanding flawless performance.', 'ans': 'perfectionists', 'ref': 'E', 'exp': 'Đoạn E: "Chronic perfectionists fall victim to paralysis, fearing anything less than an immaculate outcome".'},
        {'num': 22, 'type': 'summary_completion', 'header': 'Questions 17–22', 'inst': 'Choose ONE WORD ONLY.', 'prompt': 'The subsequent avoidance creates an overwhelming cycle of [22] …………… and regret.', 'ans': 'guilt', 'ref': 'E', 'exp': 'Đoạn E: "Short-term relief gives way to acute feelings of guilt and diminished self-efficacy".'},
        {'num': 23, 'type': 'multiple_choice', 'header': 'Questions 23–26', 'inst': 'Choose TWO letters, A–E.', 'prompt': 'Which TWO psychological strategies does the author recommend to overcome procrastination? [Choose A or C]', 'opts': ['Breaking large projects into microscopic incremental milestones', 'Enforcing severe penalties for missed self-deadlines', 'Practicing self-compassion to diminish negative emotions', 'Eliminating all leisure time until projects are finished', 'Relying exclusively on bursts of inspiration'], 'ans': 'A', 'ref': 'F', 'exp': 'Tác giả khuyến nghị chia nhỏ đầu việc thành các bước siêu nhỏ (micro-steps).'},
        {'num': 24, 'type': 'multiple_choice', 'header': 'Questions 23–26', 'inst': 'Choose TWO letters, A–E.', 'prompt': 'Which other strategy is recommended? [Choose A or C]', 'opts': ['Breaking large projects into microscopic incremental milestones', 'Enforcing severe penalties for missed self-deadlines', 'Practicing self-compassion to diminish negative emotions', 'Eliminating all leisure time until projects are finished', 'Relying exclusively on bursts of inspiration'], 'ans': 'C', 'ref': 'F', 'exp': 'Thực hành lòng trắc ẩn với bản thân (self-compassion) để hóa giải cảm xúc tội lỗi và kích hoạt hành động.'},
        {'num': 25, 'type': 'multiple_choice', 'header': 'Questions 23–26', 'inst': 'Choose TWO letters, A–E.', 'prompt': 'Which TWO workplace conditions worsen procrastination habits? [Choose A or E]', 'opts': ['Ambiguous project guidelines with undefined success metrics', 'Excessive monetary rewards for early submission', 'Strict surveillance cameras monitoring employees', 'Collaborative open-plan working spaces', 'Absence of intermediate check-in feedback from supervisors'], 'ans': 'A', 'ref': 'D', 'exp': 'Sự mơ hồ về mục tiêu và thiếu tiêu chí rõ ràng khiến não bộ chần chừ.'},
        {'num': 26, 'type': 'multiple_choice', 'header': 'Questions 23–26', 'inst': 'Choose TWO letters, A–E.', 'prompt': 'Which other workplace condition worsens procrastination? [Choose A or E]', 'opts': ['Ambiguous project guidelines with undefined success metrics', 'Excessive monetary rewards for early submission', 'Strict surveillance cameras monitoring employees', 'Collaborative open-plan working spaces', 'Absence of intermediate check-in feedback from supervisors'], 'ans': 'E', 'ref': 'D', 'exp': 'Thiếu các mốc phản hồi trung gian từ cấp trên tạo điều kiện cho sự trì hoãn kéo dài.'}
    ],
    'p3': [
        {'num': 27, 'type': 'tfng', 'header': 'Questions 27–32', 'inst': 'Do the following statements agree with the claims of the writer in Reading Passage 3? Write YES, NO, or NOT GIVEN.', 'prompt': 'Human umpires consistently achieve 100% accuracy in high-stakes baseball games.', 'opts': ['YES', 'NO', 'NOT GIVEN'], 'ans': 'NO', 'ref': 'A', 'exp': 'Đoạn A chứng minh trọng tài con người thường xuyên mắc sai sót do giới hạn sinh học về tốc độ mắt.'},
        {'num': 28, 'type': 'tfng', 'header': 'Questions 27–32', 'inst': 'Write YES, NO, or NOT GIVEN.', 'prompt': 'Automated ball-strike detection systems rely on multi-camera tracking arrays.', 'opts': ['YES', 'NO', 'NOT GIVEN'], 'ans': 'YES', 'ref': 'B', 'exp': 'Đoạn B mô tả hệ thống ABS sử dụng mạng lưới camera quang học 3D đồng bộ với radar Doppler.'},
        {'num': 29, 'type': 'tfng', 'header': 'Questions 27–32', 'inst': 'Write YES, NO, or NOT GIVEN.', 'prompt': 'Major League Baseball plans to completely eliminate human presence behind home plate.', 'opts': ['YES', 'NO', 'NOT GIVEN'], 'ans': 'NOT GIVEN', 'ref': 'C', 'exp': 'Bài đọc cho biết máy móc hỗ trợ ra quyết định nhưng không đề cập kế hoạch đuổi việc hoàn toàn trọng tài đứng sau cầu thủ.'},
        {'num': 30, 'type': 'tfng', 'header': 'Questions 27–32', 'inst': 'Write YES, NO, or NOT GIVEN.', 'prompt': 'Catchers welcomed the automated strike zone because it valued their framing skills.', 'opts': ['YES', 'NO', 'NOT GIVEN'], 'ans': 'NO', 'ref': 'D', 'exp': 'Đoạn D nêu các cầu thủ bắt bóng phản đối vì công nghệ vô hiệu hóa kỹ năng "ăn gian vị trí bắt bóng" (pitch framing) mà họ dày công luyện tập.'},
        {'num': 31, 'type': 'tfng', 'header': 'Questions 27–32', 'inst': 'Write YES, NO, or NOT GIVEN.', 'prompt': 'Weather changes frequently distort laser strike zone measurements.', 'opts': ['YES', 'NO', 'NOT GIVEN'], 'ans': 'NOT GIVEN', 'ref': 'E', 'exp': 'Bài đọc không nói thời tiết làm sai lệch việc đo đạc của tia laser.'},
        {'num': 32, 'type': 'tfng', 'header': 'Questions 27–32', 'inst': 'Write YES, NO, or NOT GIVEN.', 'prompt': 'The challenge review system preserves traditional game drama while ensuring fairness.', 'opts': ['YES', 'NO', 'NOT GIVEN'], 'ans': 'YES', 'ref': 'F', 'exp': 'Đoạn F khẳng định cơ chế quyền khiếu nại (challenge system) vừa giữ được tính kịch tính truyền thống vừa đảm bảo tính công bằng thể thao.'},
        {'num': 33, 'type': 'matching_info', 'header': 'Questions 33–37', 'inst': 'Match each statement with the correct person (A–H).', 'prompt': 'Argued that human fallibility is an inseparable component of sports heritage.', 'ans': 'F', 'ref': 'C', 'exp': 'Nhà bình luận thể thao kì cựu lập luận sự sai sót của con người là một phần di sản bóng chày.'},
        {'num': 34, 'type': 'matching_info', 'header': 'Questions 33–37', 'inst': 'Match each statement with the correct person.', 'prompt': 'Demonstrated that automated systems significantly reduce contentious disputes on the field.', 'ans': 'D', 'ref': 'D', 'exp': 'Giám đốc giải đấu chỉ ra số vụ cãi cọ và đuổi khỏi sân giảm hơn 80% khi dùng máy tự động.'},
        {'num': 35, 'type': 'matching_info', 'header': 'Questions 33–37', 'inst': 'Match each statement with the correct person.', 'prompt': 'Emphasized the psychological pressure endured by junior umpires during live telecasts.', 'ans': 'H', 'ref': 'E', 'exp': 'Cựu trọng tài chia sẻ áp lực khủng khiếp từ truyền thông khi một quyết định gây tranh cãi bị quay chậm.'},
        {'num': 36, 'type': 'matching_info', 'header': 'Questions 33–37', 'inst': 'Match each statement with the correct person.', 'prompt': 'Developed the algorithmic coordinate tracking model currently utilized by the league.', 'ans': 'B', 'ref': 'B', 'exp': 'Kỹ sư trưởng phòng nghiên cứu công nghệ phát triển thuật toán định vị tọa độ bóng 3D.'},
        {'num': 37, 'type': 'matching_info', 'header': 'Questions 33–37', 'inst': 'Match each statement with the correct person.', 'prompt': 'Stated that fan engagement increases when technology provides instant visual transparency.', 'ans': 'G', 'ref': 'F', 'exp': 'Chuyên gia tiếp thị người hâm mộ nhận định khán giả truyền hình hào hứng hơn khi thấy quỹ đạo bóng minh bạch.'},
        {'num': 38, 'type': 'multiple_choice', 'header': 'Questions 38–40', 'inst': 'Choose the correct letter, A, B, C or D.', 'prompt': 'What was the primary motive for piloting robot umpires in minor leagues?', 'opts': ['To cut administrative payroll costs', 'To test software reliability in real game conditions', 'To respond to player union strike threats', 'To eliminate the umpire profession entirely'], 'ans': 'B', 'ref': 'B', 'exp': 'Thử nghiệm ở giải hạng dưới nhằm kiểm tra độ tin cậy và xử lý lỗi kỹ thuật trước khi áp dụng ở Major League.'},
        {'num': 39, 'type': 'multiple_choice', 'header': 'Questions 38–40', 'inst': 'Choose the correct letter, A, B, C or D.', 'prompt': 'According to the author, the integration of AI into athletics suggests that', 'opts': ['human judges will vanish within a decade.', 'fans prioritize emotional drama over pure accuracy.', 'athletes will eventually be replaced by androids.', 'objective data and human agency can harmoniously coexist.'], 'ans': 'D', 'ref': 'G', 'exp': 'Tác giả kết luận công nghệ đo đạc khách quan và sự điều hành của con người có thể cùng tồn tại và bổ trợ cho nhau.'},
        {'num': 40, 'type': 'multiple_choice', 'header': 'Questions 38–40', 'inst': 'Choose the correct letter, A, B, C or D.', 'prompt': 'What tone does the author adopt in the concluding paragraph?', 'opts': ['Dismissive of modern technological trends', 'Nostalgic and deeply sentimental', 'Cautiously optimistic about symbiotic sports governance', 'Alarmist regarding unemployment among officials'], 'ans': 'C', 'ref': 'G', 'exp': 'Tác giả giữ thái độ lạc quan nhưng thận trọng về sự kết hợp giữa máy móc và phán đoán con người.'}
    ]
}

print('Writing Cambridge 20 Test 2 seeder...')
t2_code = make_seeder_code(2, cam20['2'], q_test2)
with open('scripts/seeders/cam20_test2.js', 'w', encoding='utf-8') as f:
    f.write(t2_code)

print('cam20_test2.js generated successfully!')
