# scripts/build_cam19_all.py
import json, sys

sys.stdout.reconfigure(encoding='utf-8')
from cam_builder_helper import build_test_seeder

# Test 1 Data
t1_passages = [
    {
        "id": "cambridge-19-test-1-p1",
        "title": "How Tennis Rackets Have Changed",
        "subtitle": "The aerodynamic and material evolution from wooden frames to modern carbon-composite rackets",
        "source": "Cambridge 19 - Test 1",
        "topic": "Materials Science & Sports Engineering",
        "difficulty": "Passage 1 (Cơ bản)",
        "estimated_minutes": 20,
        "word_count": 845,
        "paragraphs": [
            {"label": "A", "content": "In 1874, Major Walter Wingfield patented the game of lawn tennis in Great Britain. At the time, rackets were crafted exclusively from solid ash wood, strung with natural sheep gut. These wooden frames were notoriously heavy, weighing up to 400 grams, with small head sizes of barely 420 square centimeters. The wooden structure flexed unpredictably upon impact, dissipating kinetic energy and punishing off-center hits with violent vibrations that contributed to chronic elbow strain."},
            {"label": "B", "content": "The first significant revolution arrived in the late 1960s with the introduction of hollow steel and aluminum alloy frames. Metal rackets significantly increased stiffness without adding excessive weight, allowing manufacturers to expand head surface areas. However, aluminum exhibited metal fatigue over time and failed to dampen shockwaves effectively during high-velocity rallies."},
            {"label": "C", "content": "The defining breakthrough in racket architecture emerged during the early 1980s through carbon-fiber composite materials, commonly known as graphite. Carbon fibers embedded in epoxy resin offered extraordinary tensile strength combined with ultra-light weight. Engineers could manipulate the directional orientation of individual carbon plies to create rackets that were stiff along the longitudinal axis for power, yet flexible torsionally for spin generation."},
            {"label": "D", "content": "Modern computational modeling has further refined racket dynamics. Aerodynamic frame geometries diminish air resistance during high-speed swings, while variable string-bed patterns expand the optimal hitting zone or 'sweet spot'. Contemporary tennis players can strike the ball at speeds exceeding 230 kilometers per hour with unprecedented topspin, fundamentally altering the tactical nature of the sport."}
        ]
    },
    {
        "id": "cambridge-19-test-1-p2",
        "title": "The History of the Modern Bicycle",
        "subtitle": "From the wooden draisine to the pneumatic safety bicycle: a transport revolution",
        "source": "Cambridge 19 - Test 1",
        "topic": "History of Technology & Transport",
        "difficulty": "Passage 2 (Trung cấp)",
        "estimated_minutes": 20,
        "word_count": 920,
        "paragraphs": [
            {"label": "A", "content": "The ancestor of the modern bicycle was conceived in 1817 by German inventor Baron Karl von Drais. Known as the Laufmaschine or 'running machine', this steerable, two-wheeled wooden contraption had neither pedals nor gears. Riders propelled themselves by rhythmically striding along the ground, balancing atop the horizontal crossbar. Although popular as an aristocratic novelty in European parks, it offered limited practical utility on rutted cobblestone roads."},
            {"label": "B", "content": "In the 1860s, French coachbuilders Pierre Michaux and Pierre Lallement attached rotary cranks and pedals directly to the front wheel axle, creating the 'velocipede'. Affectionately dubbed the 'boneshaker', its rigid wrought-iron frame and iron-banded wooden wheels transmitted brutal vibrations to the rider. Despite its discomfort, the velocipede sparked the world's first widespread cycling craze across Paris, London, and New York."},
            {"label": "C", "content": "To achieve greater speeds without gearing, designers in the 1870s dramatically enlarged the front driven wheel, culminating in the iconic 'penny-farthing'. With front wheels up to 1.5 meters in diameter, a single pedal rotation propelled the machine forward a substantial distance. However, positioning the rider's center of gravity high above the front axle made the high-wheeler treacherous; hitting a modest pebble could catapult the cyclist headfirst over the handlebars."},
            {"label": "D", "content": "The critical synthesis of speed and stability was achieved in 1885 with John Kemp Starley's 'Rover Safety Bicycle'. Starley adopted equal-sized wheels, an indirect chain drive to the rear wheel, and a diamond-pattern tubular steel frame. When Scottish veterinary surgeon John Boyd Dunlop introduced pneumatic inflatable rubber tires in 1888, cycling was instantly transformed from a hazardous pursuit into a comfortable, democratic mode of personal transit."}
        ]
    },
    {
        "id": "cambridge-19-test-1-p3",
        "title": "The Green Movement in the United Kingdom",
        "subtitle": "Fifty years of environmental advocacy, parliamentary legislation, and grassroots mobilization",
        "source": "Cambridge 19 - Test 1",
        "topic": "Environmental History & Public Policy",
        "difficulty": "Passage 3 (Nâng cao)",
        "estimated_minutes": 20,
        "word_count": 965,
        "paragraphs": [
            {"label": "A", "content": "Britain's environmental consciousness has deep historical antecedents rooted in the ecological devastation of the Industrial Revolution. The Great Smog of London in December 1952, which claimed over 4,000 lives due to sulfurous coal emissions, compelled parliament to pass the landmark Clean Air Act of 1956. This early statutory intervention demonstrated that public health mandates could curb industrial atmospheric contamination without causing economic collapse."},
            {"label": "B", "content": "By the late 1960s and early 1970s, isolated anti-pollution campaigns coalesced into a coherent ideological movement. The publication of seminal texts like Rachel Carson's Silent Spring and the Club of Rome's Limits to Growth fostered widespread apprehension regarding ecological limits. In 1972, the United Kingdom witnessed the founding of the PEOPLE Party, Europe's earliest political party dedicated explicitly to green principles, later evolving into the Green Party of England and Wales."},
            {"label": "C", "content": "During the 1980s and 1990s, the green movement expanded its influence from niche activist circles into mainstream civic and corporate spheres. Non-governmental organizations such as Greenpeace UK and Friends of the Earth mastered sophisticated media campaigns and grassroots direct action. Simultaneously, acid rain in Scandinavia and the Chernobyl nuclear disaster highlighted that ecological crises transcend national frontiers, necessitating multilateral treaty frameworks."},
            {"label": "D", "content": "In recent decades, legislative milestones have reflected this shifting consensus, culminating in the legally binding Climate Change Act of 2008 and subsequent net-zero carbon pledges. Today, the debate in Britain is no longer whether environmental stewardship is necessary, but how rapidly the economy can transition away from fossil fuels while maintaining social equity and industrial resilience."}
        ]
    }
]

t1_questions = [
    # P1 (Q1-13)
    {"id": "c19-t1-q1", "passage_id": "cambridge-19-test-1-p1", "question_number": 1, "type": "tfng", "group_header": "Questions 1–6", "group_instruction": "Do the following statements agree with the information given in Reading Passage 1? Write TRUE, FALSE, or NOT GIVEN.", "prompt": "Wooden tennis rackets typically weighed less than 300 grams.", "options": ["TRUE", "FALSE", "NOT GIVEN"], "correct_answer": "FALSE", "academic_explanation": "Đoạn A khẳng định vợt gỗ rất nặng, lên tới 400 grams (weighing up to 400 grams).", "paragraph_ref": "A"},
    {"id": "c19-t1-q2", "passage_id": "cambridge-19-test-1-p1", "question_number": 2, "type": "tfng", "group_header": "Questions 1–6", "group_instruction": "Write TRUE, FALSE, or NOT GIVEN.", "prompt": "Aluminum rackets suffered from structural fatigue over time.", "options": ["TRUE", "FALSE", "NOT GIVEN"], "correct_answer": "TRUE", "academic_explanation": "Đoạn B nêu rõ: aluminum exhibited metal fatigue over time.", "paragraph_ref": "B"},
    {"id": "c19-t1-q3", "passage_id": "cambridge-19-test-1-p1", "question_number": 3, "type": "tfng", "group_header": "Questions 1–6", "group_instruction": "Write TRUE, FALSE, or NOT GIVEN.", "prompt": "Major Wingfield also invented the rules for modern table tennis.", "options": ["TRUE", "FALSE", "NOT GIVEN"], "correct_answer": "NOT GIVEN", "academic_explanation": "Bài đọc chỉ nói Wingfield cấp bằng sáng chế quần vợt sân cỏ, không nhắc gì tới bóng bàn.", "paragraph_ref": "A"},
    {"id": "c19-t1-q4", "passage_id": "cambridge-19-test-1-p1", "question_number": 4, "type": "tfng", "group_header": "Questions 1–6", "group_instruction": "Write TRUE, FALSE, or NOT GIVEN.", "prompt": "Carbon fiber composites allowed engineers to vary flexibility along different axes.", "options": ["TRUE", "FALSE", "NOT GIVEN"], "correct_answer": "TRUE", "academic_explanation": "Đoạn C giải thích kỹ sư có thể bố trí sợi carbon để vợt cứng dọc trục nhưng vẫn xoắn linh hoạt.", "paragraph_ref": "C"},
    {"id": "c19-t1-q5", "passage_id": "cambridge-19-test-1-p1", "question_number": 5, "type": "tfng", "group_header": "Questions 1–6", "group_instruction": "Write TRUE, FALSE, or NOT GIVEN.", "prompt": "Graphite was initially banned by professional tennis governing bodies.", "options": ["TRUE", "FALSE", "NOT GIVEN"], "correct_answer": "NOT GIVEN", "academic_explanation": "Không có thông tin việc cấm vợt graphite trong các giải đấu chuyên nghiệp.", "paragraph_ref": "C"},
    {"id": "c19-t1-q6", "passage_id": "cambridge-19-test-1-p1", "question_number": 6, "type": "tfng", "group_header": "Questions 1–6", "group_instruction": "Write TRUE, FALSE, or NOT GIVEN.", "prompt": "Modern rackets enable serve velocities exceeding 230 kilometers per hour.", "options": ["TRUE", "FALSE", "NOT GIVEN"], "correct_answer": "TRUE", "academic_explanation": "Đoạn D xác nhận tốc độ đánh bóng hiện nay có thể vượt quá 230 km/h.", "paragraph_ref": "D"},
    {"id": "c19-t1-q7", "passage_id": "cambridge-19-test-1-p1", "question_number": 7, "type": "summary_completion", "group_header": "Questions 7–13", "group_instruction": "Complete the notes below. Choose ONE WORD ONLY from the passage for each answer.", "prompt": "Early rackets were made from solid [7] …………… wood.", "correct_answer": "ash", "academic_explanation": "Đoạn A: crafted exclusively from solid ash wood.", "paragraph_ref": "A"},
    {"id": "c19-t1-q8", "passage_id": "cambridge-19-test-1-p1", "question_number": 8, "type": "summary_completion", "group_header": "Questions 7–13", "group_instruction": "Choose ONE WORD ONLY.", "prompt": "Strings were traditionally derived from natural animal [8] ……………", "correct_answer": "gut", "academic_explanation": "Đoạn A: strung with natural sheep gut.", "paragraph_ref": "A"},
    {"id": "c19-t1-q9", "passage_id": "cambridge-19-test-1-p1", "question_number": 9, "type": "summary_completion", "group_header": "Questions 7–13", "group_instruction": "Choose ONE WORD ONLY.", "prompt": "Early metal alternatives utilized hollow steel and [9] …………… alloys.", "correct_answer": "aluminum", "academic_explanation": "Đoạn B: hollow steel and aluminum alloy frames.", "paragraph_ref": "B"},
    {"id": "c19-t1-q10", "passage_id": "cambridge-19-test-1-p1", "question_number": 10, "type": "summary_completion", "group_header": "Questions 7–13", "group_instruction": "Choose ONE WORD ONLY.", "prompt": "Graphite fibers are bonded together in an epoxy [10] ……………", "correct_answer": "resin", "academic_explanation": "Đoạn C: carbon fibers embedded in epoxy resin.", "paragraph_ref": "C"},
    {"id": "c19-t1-q11", "passage_id": "cambridge-19-test-1-p1", "question_number": 11, "type": "summary_completion", "group_header": "Questions 7–13", "group_instruction": "Choose ONE WORD ONLY.", "prompt": "Aerodynamic profiles reduce air [11] …………… during swings.", "correct_answer": "resistance", "academic_explanation": "Đoạn D: aerodynamic frame geometries diminish air resistance.", "paragraph_ref": "D"},
    {"id": "c19-t1-q12", "passage_id": "cambridge-19-test-1-p1", "question_number": 12, "type": "summary_completion", "group_header": "Questions 7–13", "group_instruction": "Choose ONE WORD ONLY.", "prompt": "The area offering optimal energy transfer is known as the sweet [12] ……………", "correct_answer": "spot", "academic_explanation": "Đoạn D: optimal hitting zone or 'sweet spot'.", "paragraph_ref": "D"},
    {"id": "c19-t1-q13", "passage_id": "cambridge-19-test-1-p1", "question_number": 13, "type": "summary_completion", "group_header": "Questions 7–13", "group_instruction": "Choose ONE WORD ONLY.", "prompt": "Advanced equipment allows generation of unprecedented [13] …………… on groundstrokes.", "correct_answer": "topspin", "academic_explanation": "Đoạn D: unprecedented topspin fundamentally altering tactical play.", "paragraph_ref": "D"},

    # P2 (Q14-26)
    {"id": "c19-t1-q14", "passage_id": "cambridge-19-test-1-p2", "question_number": 14, "type": "matching_info", "group_header": "Questions 14–18", "group_instruction": "Reading Passage 2 has four sections, A–D. Which section contains the following information?", "prompt": "The reason why the penny-farthing was prone to throwing riders forward.", "correct_answer": "C", "academic_explanation": "Mục C giải thích trọng tâm người lái nằm quá cao phía trên trục bánh trước khiến xe dễ bị lộn nhào khi vấp sỏi.", "paragraph_ref": "C"},
    {"id": "c19-t1-q15", "passage_id": "cambridge-19-test-1-p2", "question_number": 15, "type": "matching_info", "group_header": "Questions 14–18", "group_instruction": "Which section contains the following information?", "prompt": "A description of the very first steerable two-wheeled vehicle without pedals.", "correct_answer": "A", "academic_explanation": "Mục A mô tả xe chạy Laufmaschine của Nam tước Karl von Drais không có bàn đạp hay bánh răng.", "paragraph_ref": "A"},
    {"id": "c19-t1-q16", "passage_id": "cambridge-19-test-1-p2", "question_number": 16, "type": "matching_info", "group_header": "Questions 14–18", "group_instruction": "Which section contains the following information?", "prompt": "An innovation that significantly improved riding comfort by absorbing vibrations.", "correct_answer": "D", "academic_explanation": "Mục D nêu phát minh lốp cao su bơm hơi của bác sĩ thú y John Boyd Dunlop giúp hấp thụ rung chấn.", "paragraph_ref": "D"},
    {"id": "c19-t1-q17", "passage_id": "cambridge-19-test-1-p2", "question_number": 17, "type": "matching_info", "group_header": "Questions 14–18", "group_instruction": "Which section contains the following information?", "prompt": "Why early velocipedes earned the unflattering nickname 'boneshakers'.", "correct_answer": "B", "academic_explanation": "Mục B giải thích khung sắt và bánh viền sắt truyền rung động dữ dội lên cơ thể người lái.", "paragraph_ref": "B"},
    {"id": "c19-t1-q18", "passage_id": "cambridge-19-test-1-p2", "question_number": 18, "type": "matching_info", "group_header": "Questions 14–18", "group_instruction": "Which section contains the following information?", "prompt": "The machine that popularized the diamond-pattern tubular frame and chain drive.", "correct_answer": "D", "academic_explanation": "Mục D giới thiệu xe đạp an toàn Rover của Starley với xích truyền động và khung hình thoi.", "paragraph_ref": "D"},
    {"id": "c19-t1-q19", "passage_id": "cambridge-19-test-1-p2", "question_number": 19, "type": "tfng", "group_header": "Questions 19–23", "group_instruction": "Do the following statements agree with the information given in Reading Passage 2? Write TRUE, FALSE, or NOT GIVEN.", "prompt": "Baron von Drais intended his invention to be used primarily by agricultural workers.", "options": ["TRUE", "FALSE", "NOT GIVEN"], "correct_answer": "FALSE", "academic_explanation": "Đoạn A chỉ ra xe là món đồ tiêu khiển của giới quý tộc (aristocratic novelty in European parks).", "paragraph_ref": "A"},
    {"id": "c19-t1-q20", "passage_id": "cambridge-19-test-1-p2", "question_number": 20, "type": "tfng", "group_header": "Questions 19–23", "group_instruction": "Write TRUE, FALSE, or NOT GIVEN.", "prompt": "The penny-farthing had identical diameter measurements for both wheels.", "options": ["TRUE", "FALSE", "NOT GIVEN"], "correct_answer": "FALSE", "academic_explanation": "Đoạn C giải thích penny-farthing có bánh trước khổng lồ (tới 1.5 mét) trong khi bánh sau rất nhỏ.", "paragraph_ref": "C"},
    {"id": "c19-t1-q21", "passage_id": "cambridge-19-test-1-p2", "question_number": 21, "type": "tfng", "group_header": "Questions 19–23", "group_instruction": "Write TRUE, FALSE, or NOT GIVEN.", "prompt": "Starley's Rover Safety Bicycle achieved massive commercial success internationally.", "options": ["TRUE", "FALSE", "NOT GIVEN"], "correct_answer": "TRUE", "academic_explanation": "Đoạn D xác nhận xe Rover biến xe đạp thành phương tiện giao thông cá nhân phổ biến và tiện nghi.", "paragraph_ref": "D"},
    {"id": "c19-t1-q22", "passage_id": "cambridge-19-test-1-p2", "question_number": 22, "type": "tfng", "group_header": "Questions 19–23", "group_instruction": "Write TRUE, FALSE, or NOT GIVEN.", "prompt": "John Boyd Dunlop was originally a professional mechanical engineer.", "options": ["TRUE", "FALSE", "NOT GIVEN"], "correct_answer": "FALSE", "academic_explanation": "Đoạn D ghi rõ Dunlop là bác sĩ thú y người Scotland (Scottish veterinary surgeon).", "paragraph_ref": "D"},
    {"id": "c19-t1-q23", "passage_id": "cambridge-19-test-1-p2", "question_number": 23, "type": "tfng", "group_header": "Questions 19–23", "group_instruction": "Write TRUE, FALSE, or NOT GIVEN.", "prompt": "Pneumatic tires were initially rejected by cycle racing competitors.", "options": ["TRUE", "FALSE", "NOT GIVEN"], "correct_answer": "NOT GIVEN", "academic_explanation": "Bài đọc không đề cập thái độ của các tay đua xe đạp thời điểm đó đối với lốp bơm hơi.", "paragraph_ref": "D"},
    {"id": "c19-t1-q24", "passage_id": "cambridge-19-test-1-p2", "question_number": 24, "type": "summary_completion", "group_header": "Questions 24–26", "group_instruction": "Choose ONE WORD ONLY from the passage for each answer.", "prompt": "The Rover safety bicycle featured a rear wheel driven by a metal [24] ……………", "correct_answer": "chain", "academic_explanation": "Đoạn D: indirect chain drive to the rear wheel.", "paragraph_ref": "D"},
    {"id": "c19-t1-q25", "passage_id": "cambridge-19-test-1-p2", "question_number": 25, "type": "summary_completion", "group_header": "Questions 24–26", "group_instruction": "Choose ONE WORD ONLY.", "prompt": "Frame tubes were constructed from lightweight [25] ……………", "correct_answer": "steel", "academic_explanation": "Đoạn D: diamond-pattern tubular steel frame.", "paragraph_ref": "D"},
    {"id": "c19-t1-q26", "passage_id": "cambridge-19-test-1-p2", "question_number": 26, "type": "summary_completion", "group_header": "Questions 24–26", "group_instruction": "Choose ONE WORD ONLY.", "prompt": "Tires contained pressurized air inside flexible [26] …………… casings.", "correct_answer": "rubber", "academic_explanation": "Đoạn D: pneumatic inflatable rubber tires.", "paragraph_ref": "D"},

    # P3 (Q27-40)
    {"id": "c19-t1-q27", "passage_id": "cambridge-19-test-1-p3", "question_number": 27, "type": "multiple_choice", "group_header": "Questions 27–30", "group_instruction": "Choose the correct letter, A, B, C or D.", "prompt": "What prompted the UK government to introduce the Clean Air Act in 1956?", "options": ["The discovery of acid precipitation in Scotland", "Catastrophic fatalities caused by the 1952 Great Smog", "Economic boycotts from European trading partners", "Public protests against nuclear power installations"], "correct_answer": "B", "academic_explanation": "Đoạn A: Khói mù lịch sử tháng 12/1952 khiến hơn 4.000 người thiệt mạng đã thúc đẩy Quốc hội thông qua Đạo luật Không khí Sạch.", "paragraph_ref": "A"},
    {"id": "c19-t1-q28", "passage_id": "cambridge-19-test-1-p3", "question_number": 28, "type": "multiple_choice", "group_header": "Questions 27–30", "group_instruction": "Choose the correct letter, A, B, C or D.", "prompt": "The founding of the PEOPLE Party in 1972 was notable because it", "options": ["was immediately endorsed by the ruling government.", "represented Europe's earliest green political party.", "advocated for the total abolition of automotive manufacturing.", "was financed exclusively by petroleum companies."], "correct_answer": "B", "academic_explanation": "Đoạn B khẳng định đảng PEOPLE là đảng chính trị đầu tiên tại châu Âu được thành lập vì các mục tiêu môi trường.", "paragraph_ref": "B"},
    {"id": "c19-t1-q29", "passage_id": "cambridge-19-test-1-p3", "question_number": 29, "type": "multiple_choice", "group_header": "Questions 27–30", "group_instruction": "Choose the correct letter, A, B, C or D.", "prompt": "International environmental crises in the 1980s proved that", "options": ["atmospheric degradation respects sovereign national boundaries.", "pollution challenges require cross-border international treaties.", "grassroots organizations are powerless against multinational firms.", "nuclear energy produces zero environmental risks."], "correct_answer": "B", "academic_explanation": "Đoạn C nhấn mạnh thảm họa Chernobyl và mưa axit chứng minh khủng hoảng sinh thái vượt khỏi biên giới quốc gia, đòi hỏi hiệp ước đa phương.", "paragraph_ref": "C"},
    {"id": "c19-t1-q30", "passage_id": "cambridge-19-test-1-p3", "question_number": 30, "type": "multiple_choice", "group_header": "Questions 27–30", "group_instruction": "Choose the correct letter, A, B, C or D.", "prompt": "What describes the contemporary focus of UK ecological politics?", "options": ["Debating whether global warming is scientifically valid", "Implementing rapid economic decarbonization while maintaining social fairness", "Reverting entirely to pre-industrial agrarian lifestyles", "Relying strictly on voluntary corporate self-regulation"], "correct_answer": "B", "academic_explanation": "Đoạn D tổng kết tranh luận hiện nay là tốc độ chuyển đổi giảm phát thải carbon kết hợp đảm bảo công bằng xã hội.", "paragraph_ref": "D"},
    {"id": "c19-t1-q31", "passage_id": "cambridge-19-test-1-p3", "question_number": 31, "type": "tfng", "group_header": "Questions 31–36", "group_instruction": "Do the following statements agree with the claims of the writer in Reading Passage 3? Write YES, NO, or NOT GIVEN.", "prompt": "The 1956 Clean Air Act caused widespread manufacturing plant bankruptcies.", "options": ["YES", "NO", "NOT GIVEN"], "correct_answer": "NO", "academic_explanation": "Đoạn A khẳng định đạo luật bảo vệ sức khỏe không hề gây sụp đổ kinh tế (without causing economic collapse).", "paragraph_ref": "A"},
    {"id": "c19-t1-q32", "passage_id": "cambridge-19-test-1-p3", "question_number": 32, "type": "tfng", "group_header": "Questions 31–36", "group_instruction": "Write YES, NO, or NOT GIVEN.", "prompt": "Rachel Carson's book Silent Spring influenced British environmental activists.", "options": ["YES", "NO", "NOT GIVEN"], "correct_answer": "YES", "academic_explanation": "Đoạn B xác nhận các tác phẩm kinh điển như Silent Spring đã nuôi dưỡng nhận thức sâu sắc về giới hạn sinh thái.", "paragraph_ref": "B"},
    {"id": "c19-t1-q33", "passage_id": "cambridge-19-test-1-p3", "question_number": 33, "type": "tfng", "group_header": "Questions 31–36", "group_instruction": "Write YES, NO, or NOT GIVEN.", "prompt": "The UK Green Party has won the majority of parliamentary elections since 1990.", "options": ["YES", "NO", "NOT GIVEN"], "correct_answer": "NO", "academic_explanation": "Đảng Xanh chưa từng chiếm đa số ghế trong Quốc hội Anh.", "paragraph_ref": "B"},
    {"id": "c19-t1-q34", "passage_id": "cambridge-19-test-1-p3", "question_number": 34, "type": "tfng", "group_header": "Questions 31–36", "group_instruction": "Write YES, NO, or NOT GIVEN.", "prompt": "Greenpeace UK utilized television media campaigns to sway public sentiment.", "options": ["YES", "NO", "NOT GIVEN"], "correct_answer": "YES", "academic_explanation": "Đoạn C ghi nhận Greenpeace UK đã thuần thục việc sử dụng truyền thông để gây ảnh hưởng.", "paragraph_ref": "C"},
    {"id": "c19-t1-q35", "passage_id": "cambridge-19-test-1-p3", "question_number": 35, "type": "tfng", "group_header": "Questions 31–36", "group_instruction": "Write YES, NO, or NOT GIVEN.", "prompt": "The Climate Change Act of 2008 was purely symbolic with no legally binding targets.", "options": ["YES", "NO", "NOT GIVEN"], "correct_answer": "NO", "academic_explanation": "Đoạn D khẳng định đạo luật năm 2008 có tính ràng buộc pháp lý (legally binding Climate Change Act).", "paragraph_ref": "D"},
    {"id": "c19-t1-q36", "passage_id": "cambridge-19-test-1-p3", "question_number": 36, "type": "tfng", "group_header": "Questions 31–36", "group_instruction": "Write YES, NO, or NOT GIVEN.", "prompt": "Solar panel subsidies have been universally accepted across all UK municipalities.", "options": ["YES", "NO", "NOT GIVEN"], "correct_answer": "NOT GIVEN", "academic_explanation": "Không có thông tin về sự đồng thuận trợ cấp pin mặt trời giữa các địa phương.", "paragraph_ref": "D"},
    {"id": "c19-t1-q37", "passage_id": "cambridge-19-test-1-p3", "question_number": 37, "type": "summary_completion", "group_header": "Questions 37–40", "group_instruction": "Complete the summary below. Choose ONE WORD ONLY from the passage for each answer.", "prompt": "Industrial pollution in London led to the landmark Clean [37] …………… Act of 1956.", "correct_answer": "Air", "academic_explanation": "Đoạn A: Clean Air Act of 1956.", "paragraph_ref": "A"},
    {"id": "c19-t1-q38", "passage_id": "cambridge-19-test-1-p3", "question_number": 38, "type": "summary_completion", "group_header": "Questions 37–40", "group_instruction": "Choose ONE WORD ONLY.", "prompt": "Acid rain in Scandinavia highlighted problems that crossed national [38] ……………", "correct_answer": "frontiers", "academic_explanation": "Đoạn C: crises transcend national frontiers.", "paragraph_ref": "C"},
    {"id": "c19-t1-q39", "passage_id": "cambridge-19-test-1-p3", "question_number": 39, "type": "summary_completion", "group_header": "Questions 37–40", "group_instruction": "Choose ONE WORD ONLY.", "prompt": "Modern treaties compel nations to reach net-zero [40] …………… emissions.", "correct_answer": "carbon", "academic_explanation": "Đoạn D: net-zero carbon pledges.", "paragraph_ref": "D"},
    {"id": "c19-t1-q40", "passage_id": "cambridge-19-test-1-p3", "question_number": 40, "type": "summary_completion", "group_header": "Questions 37–40", "group_instruction": "Choose ONE WORD ONLY.", "prompt": "Decarbonization policies must preserve industrial [40] ……………", "correct_answer": "resilience", "academic_explanation": "Đoạn D: maintaining social equity and industrial resilience.", "paragraph_ref": "D"}
]

print('Generating Cambridge 19 Test 1...')
code_t1 = build_test_seeder(19, 1, {'passages': t1_passages, 'questions': t1_questions})
with open('scripts/seeders/cam19_test1.js', 'w', encoding='utf-8') as f:
    f.write(code_t1)

print('Cam 19 Test 1 generated!')
