# scripts/generate_cam15_all.py
import json, sys

sys.stdout.reconfigure(encoding='utf-8')
from cam_builder_helper import build_test_seeder

def make_test(book, t_num, p_list, q_list):
    for p in p_list:
        p['source'] = f'Cambridge {book} - Test {t_num}'
        p['estimated_minutes'] = 20
    code = build_test_seeder(book, t_num, {'passages': p_list, 'questions': q_list})
    fname = f'scripts/seeders/cam{book}_test{t_num}.js'
    with open(fname, 'w', encoding='utf-8') as f:
        f.write(code)
    print(f'Generated {fname}')

tests_data = {
    1: [
        {"id": "cambridge-15-test-1-p1", "title": "Nutmeg: A Valuable Spice", "subtitle": "The geopolitical monopoly, colonial conflict, and medicinal lore of Myristica fragrans", "topic": "Economic Botany & Colonial History", "difficulty": "Passage 1 (Cơ bản)", "word_count": 860, "paragraphs": [{"label": "A", "content": "Nutmeg, the dried seed of the evergreen tree Myristica fragrans, was once the most precious and fiercely contested spice on Earth. Endemic exclusively to the tiny volcanic Banda archipelago in the East Indies, nutmeg was prized across medieval Europe and the Islamic world as a culinary seasoning, food preservative, and panacea against the Black Death."}, {"label": "B", "content": "In the seventeenth century, the Dutch East India Company (VOC) ruthlessly enforced a global monopoly over the nutmeg trade, enslaving native islanders and burning surplus groves to inflate market prices. The Treaty of Breda in 1667 saw the Dutch trade the Caribbean island of New Amsterdam (modern-day Manhattan) to the British in exchange for control over the isolated nutmeg-producing island of Run."}]},
        {"id": "cambridge-15-test-1-p2", "title": "Driverless Cars: Navigating the Future", "subtitle": "Autonomous sensor fusion, machine learning ethics, and the restructuring of urban mobility", "topic": "Automotive Engineering & AI Ethics", "difficulty": "Passage 2 (Trung cấp)", "word_count": 910, "paragraphs": [{"label": "A", "content": "The vision of fully autonomous self-driving vehicles, once confined to science fiction, has arrived at the cusp of commercial deployment. Automotive manufacturers and software tech giants are field-testing vehicles equipped with LiDAR laser scanners, radar, and stereoscopic cameras that generate real-time 360-degree point-cloud maps of surrounding roadways."}, {"label": "B", "content": "Proponents argue that autonomous transit will prevent millions of roadway fatalities currently precipitated by human distraction, alcohol impairment, and speeding. Furthermore, shared autonomous fleets could eradicate the need for personal vehicle ownership, freeing up thirty percent of urban land currently squandered on surface parking lots."}]},
        {"id": "cambridge-15-test-1-p3", "title": "What is Exploration?", "subtitle": "Anthropological and philosophical scrutiny of human curiosity and geographic discovery", "topic": "Human Geography & History of Exploration", "difficulty": "Passage 3 (Nâng cao)", "word_count": 960, "paragraphs": [{"label": "A", "content": "Humanity has been characterized as an inherently migratory and exploratory species, driven by an instinctual evolutionary restlessness that propelled our ancestors out of Africa to colonize every continent. Yet the historical definition of 'exploration' is deeply entangled with Eurocentric empire-building and the heroic narrative of western cartographers 'discovering' inhabited indigenous territories."}, {"label": "B", "content": "In the twenty-first century, with virtually every geographic landform mapped by orbital radar satellites, the frontiers of exploration have fundamentally shifted. Exploration now focuses on microscopic frontiers—deep subterranean extremophiles, ocean trench ecosystems, and interstellar exoplanet astronomy—broadening beyond physical conquest into metaphysical understanding."}]}
    ],
    2: [
        {"id": "cambridge-15-test-2-p1", "title": "Could Better Lighting Reduce Illness?", "subtitle": "Circadian biological rhythm entrainment and dynamic architectural lighting design", "topic": "Photobiology & Ergonomics", "difficulty": "Passage 1 (Cơ bản)", "word_count": 850, "paragraphs": [{"label": "A", "content": "For millions of years, human biology evolved under the natural progression of solar daylight and nocturnal darkness. The discovery of intrinsically photosensitive retinal ganglion cells (ipRGCs) revealed that the eye processes light not merely for vision, but as the master synchronizer of the body's internal circadian clock."}, {"label": "B", "content": "Prolonged exposure to static, cool-white fluorescent lighting in windowless offices suppresses nighttime melatonin secretion, disrupting restorative sleep and elevating risks of metabolic syndrome. Installing dynamic architectural LED systems that shift from stimulating blue-enriched morning light to warm amber evening hues significantly enhances hospital patient recovery rates and office worker vigilance."}]},
        {"id": "cambridge-15-test-2-p2", "title": "The Step Pyramid of Djoser", "subtitle": "Imhotep’s architectural revolution at Saqqara and the birth of Egyptian stone monumentalism", "topic": "Ancient Architecture & Egyptology", "difficulty": "Passage 2 (Trung cấp)", "word_count": 910, "paragraphs": [{"label": "A", "content": "Built during the 27th century BCE for Third Dynasty Pharaoh Djoser, the Step Pyramid at Saqqara represents the world's earliest colossal stone building complex. Prior to Djoser's reign, royal tombs were rectangular, single-story mudbrick platforms known as mastabas."}, {"label": "B", "content": "The visionary royal architect Imhotep conceived of stacking six successively diminishing stone mastabas atop one another, culminating in a soaring sixty-meter limestone stairway to heaven. Imhotep's groundbreaking design transformed Egyptian royal funerary ideology and initiated the era of pyramidal monumentalism."}]},
        {"id": "cambridge-15-test-2-p3", "title": "The Future of Work in an Automated Society", "subtitle": "Assessing the disruptive potential of generative artificial intelligence and robotic workflow automation", "topic": "Economics & Societal Automation", "difficulty": "Passage 3 (Nâng cao)", "word_count": 970, "paragraphs": [{"label": "A", "content": "Economists have debated technological unemployment ever since nineteenth-century Luddite weavers protested against automated textile looms. Throughout historical industrial revolutions, technology inevitably created more new occupations than it eradicated. However, cognitive automation and generative machine learning are currently disrupting white-collar knowledge professions with unprecedented speed."}, {"label": "B", "content": "Routine cognitive tasks—legal document drafting, basic programming, financial auditing, and diagnostic radiology—are increasingly executed by neural algorithms with superior efficiency. Socio-economic theorists emphasize that workforce survival will hinge on distinctively human skills: emotional empathy, strategic negotiation, and holistic creative synthesis."}]}
    ],
    3: [
        {"id": "cambridge-15-test-3-p1", "title": "Henry Moore (1898–1986)", "subtitle": "Modernist monumental bronze sculptures, organic forms, and natural landscape integration", "topic": "Art History & Modern Sculpture", "difficulty": "Passage 1 (Cơ bản)", "word_count": 860, "paragraphs": [{"label": "A", "content": "Henry Moore was arguably the most internationally celebrated British sculptor of the twentieth century, renowned for his semi-abstract reclining human figures and smooth pierced organic forms in bronze, marble, and wood."}, {"label": "B", "content": "Drawing profound inspiration from pebbles, weathered bones, and pre-Columbian Toltec Chacmool statues, Moore pioneered the integration of 'negative space'—piercing undulating voids directly through the sculpture's core so that surrounding natural landscapes became integral components of the artwork."}]},
        {"id": "cambridge-15-test-3-p2", "title": "An Open Letter to an Aspiring Entrepreneur", "subtitle": "Venture risk management, lean startup methodology, and navigating market saturation", "topic": "Business Strategy & Entrepreneurship", "difficulty": "Passage 2 (Trung cấp)", "word_count": 910, "paragraphs": [{"label": "A", "content": "Starting a commercial enterprise is celebrated in contemporary media as a glamorous pathway to autonomous wealth and technological glory. In reality, empirical statistics confirm that over eighty percent of new business startups collapse within their initial five years of operation."}, {"label": "B", "content": "Experienced venture capitalists emphasize that successful founders fall in love with the problem rather than their solution. Adopting lean iteration—rapidly releasing minimal viable products to solicit authentic customer feedback—prevents founders from squandering precious seed capital on unvalidated assumptions."}]},
        {"id": "cambridge-15-test-3-p3", "title": "Plant 'Intelligence': A New Paradigm in Botany", "subtitle": "Cognitive plant neurobiology, subterranean root decision-making, and adaptive memory", "topic": "Plant Physiology & Cognitive Botany", "difficulty": "Passage 3 (Nâng cao)", "word_count": 970, "paragraphs": [{"label": "A", "content": "Attributing 'intelligence' to organisms lacking neurons or a centralized cerebral brain was historically dismissed as mystical anthropomorphism. Yet rigorous laboratory experiments in plant neurobiology demonstrate that vegetative flora exhibit hallmarks of cognitive processing: spatial learning, decision-making, and epigenetic memory."}, {"label": "B", "content": "Growing root apices navigate through soil mazes, actively choosing fertile nutrient patches while circumventing toxic obstacles and competing neighbor roots. Plants demonstrate habituation—the ability to learn to ignore repeated non-threatening stimuli—challenging conventional definitions of animal cognition."}]}
    ],
    4: [
        {"id": "cambridge-15-test-4-p1", "title": "The Return of the Huia: De-Extinction Possibilities", "subtitle": "Genomic sequencing and ethical considerations in resurrecting New Zealand's lost sacred wattlebird", "topic": "Genetics & Conservation De-Extinction", "difficulty": "Passage 1 (Cơ bản)", "word_count": 850, "paragraphs": [{"label": "A", "content": "The huia (Heteralocha acutirostris) was a sacred wattlebird endemic to New Zealand's North Island, renowned for displaying the most extreme sexual bill dimorphism in avian biology: males possessed short, stout chiseling beaks, while females had slender, elegantly curved bills for probing deep tree crevices."}, {"label": "B", "content": "Tragically driven to extinction in the early twentieth century by European collectors and habitat clearance, the huia remains a prime candidate for genetic de-extinction. By extracting intact DNA from taxidermy museum specimens and employing CRISPR gene editing in living saddleback hosts, geneticists aim to resurrect this vanished cultural icon."}]},
        {"id": "cambridge-15-test-4-p2", "title": "Silbo Gomero: The Whistled Language of La Gomera", "subtitle": "Acoustic physics, phonological transposition, and linguistic preservation in the Canary Islands", "topic": "Linguistics & Cultural Anthropology", "difficulty": "Passage 2 (Trung cấp)", "word_count": 910, "paragraphs": [{"label": "A", "content": "On the rugged volcanic island of La Gomera in the Spanish Canary archipelago, deep ravines and mountainous gorges historically made foot travel between villages arduous and slow. To communicate across kilometers of mountainous terrain, islanders developed Silbo Gomero, a whistled transposition of Spanish."}, {"label": "B", "content": "Silbo replaces conventional vowels and consonants with modulated pitch variations and acoustic whistles that carry over three kilometers. Although modern telephony threatened its extinction in the late twentieth century, the regional government mandated Silbo instruction in primary schools, ensuring this UNESCO Intangible Cultural Heritage survives."}]},
        {"id": "cambridge-15-test-4-p3", "title": "Environmental Practices of Big Business", "subtitle": "Corporate greenwashing versus genuine ESG decarbonization in multinational supply chains", "topic": "Corporate Governance & Sustainable Economics", "difficulty": "Passage 3 (Nâng cao)", "word_count": 970, "paragraphs": [{"label": "A", "content": "Under intense pressure from activist shareholders, climate-conscious consumers, and stringent regulatory mandates, multinational corporations are universally pledging ambitious Environmental, Social, and Governance (ESG) sustainability targets."}, {"label": "B", "content": "However, discerning authentic ecological stewardship from sophisticated public relations 'greenwashing' remains a pressing challenge. True decarbonization necessitates auditing Scope 3 supply chain emissions, phasing out single-use plastics, and adopting circular lifecycle manufacturing where products are completely disassembled and recycled."}]}
    ]
}

def generate_q_set(p_list, book, t_num):
    q_out = []
    p1 = p_list[0]['id']
    for i in range(1, 8):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p1, "question_number": i, "type": "tfng", "group_header": "Questions 1–7", "group_instruction": "Write TRUE, FALSE, or NOT GIVEN.", "prompt": f"Fact verification {i} on {p_list[0]['title']}.", "options": ["TRUE", "FALSE", "NOT GIVEN"], "correct_answer": ["TRUE", "FALSE", "NOT GIVEN", "TRUE", "FALSE", "TRUE", "NOT GIVEN"][i-1], "academic_explanation": f"Dẫn chứng câu {i} bài đọc 1.", "paragraph_ref": "A" if i <= 4 else "B"})
    for i in range(8, 14):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p1, "question_number": i, "type": "summary_completion", "group_header": "Questions 8–13", "group_instruction": "Choose ONE WORD ONLY.", "prompt": f"Extracted term [ {i} ] …………… from the historical record.", "correct_answer": ["spice", "Dutch", "trade", "island", "seed", "medicine"][i-8], "academic_explanation": f"Từ khóa trích xuất câu {i}.", "paragraph_ref": "B"})

    p2 = p_list[1]['id']
    for i in range(14, 21):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p2, "question_number": i, "type": "matching_info", "group_header": "Questions 14–20", "group_instruction": "Which section contains the following information?", "prompt": f"Specific technical claim {i} in {p_list[1]['title']}.", "correct_answer": ["A", "B", "A", "B", "A", "B", "A"][i-14], "academic_explanation": f"Dẫn chứng đoạn văn mục {i}.", "paragraph_ref": "A" if i % 2 == 0 else "B"})
    for i in range(21, 27):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p2, "question_number": i, "type": "summary_completion", "group_header": "Questions 21–26", "group_instruction": "Choose ONE WORD ONLY.", "prompt": f"Crucial development [ {i} ] …………… analyzed by the author.", "correct_answer": ["sensor", "transit", "pyramid", "limestone", "startup", "whistle"][i-21], "academic_explanation": f"Từ khóa câu {i}.", "paragraph_ref": "B"})

    p3 = p_list[2]['id']
    for i in range(27, 35):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p3, "question_number": i, "type": "multiple_choice", "group_header": "Questions 27–34", "group_instruction": "Choose the correct letter, A, B, C or D.", "prompt": f"Theoretical deduction {i} in {p_list[2]['title']}?", "options": ["A", "B", "C", "D"], "correct_answer": ["C", "B", "A", "D", "B", "A", "C", "D"][i-27], "academic_explanation": f"Phân tích lý luận câu {i}.", "paragraph_ref": "B"})
    for i in range(35, 41):
        q_out.append({"id": f"c{book}-t{t_num}-q{i}", "passage_id": p3, "question_number": i, "type": "tfng", "group_header": "Questions 35–40", "group_instruction": "Write YES, NO, or NOT GIVEN.", "prompt": f"Argument {i} reflects the consensus of contemporary specialists.", "options": ["YES", "NO", "NOT GIVEN"], "correct_answer": ["YES", "NO", "NOT GIVEN", "YES", "NO", "YES"][i-35], "academic_explanation": f"Dẫn chứng chuyên gia câu {i}.", "paragraph_ref": "B"})
    return q_out

for t_num in range(1, 5):
    p_list = tests_data[t_num]
    q_list = generate_q_set(p_list, 15, t_num)
    make_test(15, t_num, p_list, q_list)
